### PR TITLE
Send redirects as relative URL (without Host)

### PR DESCRIPTION
**Pull request by aquamatthias**
sendRedirect does always specify the host.
use a separate method for that.

### CODE REVIEW

**Comment by aquamatthias** [comment]
Cherry pick for 0.11

**Comment by aquamatthias** [comment]
Fixes #2267

**Comment by gkleiman** [comment]
:+1: 

But I still think people should fix their proxy configurations instead of relying on this =).

**Comment by bobrik** [comment]
@gkleiman I still don't get how to "fix" proxy configuration (see 1 https://github.com/mesosphere/marathon/pull/1973#issuecomment-142875243).

:+1: for this PR, though.

**Pull request merged**
