### PR TITLE
Simplify and cleanup start actors

### PR DESCRIPTION
**Pull request by sttts**
- remove withHealthChecks parameter from start actors. This is not used in the code.
- add proper, useful log messages to the StartingBehaviour in order to follow what the actors actually do
- factor out long, duplicated boilerplate code in TaskStartActorTest
- make StartingBehaviour more similar to TaskReplaceActor

### CODE REVIEW

**Comment by drexin** [comment]
@sttts Please always do a full test run before committing. The compilation also triggers the code reformatter.

**Comment by sttts** [comment]
Oops, you are right. 

In fact, I noticed that there is a case where we need the scaleTo parameter to the start actor: when a group is deployed, the apps are first created with zero instances and then (following the dependency graph) scaled up.

Reworking the patch....

**Comment by sttts** [comment]
As a rule of thumb, should the results of the code reformatter always be used? Have ignored them until now.

**Comment by drexin** [comment]
Yes, that's why we have it ;-)

**Comment by sttts** [comment]
Ok, great. Was wondering before where this occasional reformatting comes from :)

**Comment by drexin** [comment]
@sttts Does this fix anything? If not, I would like to postpone this until after 0.8.0 has been released.

**Comment by sttts** [comment]
Sure, it's not critical. Do you plan an only-critical-bugs freeze soon to get 0.8.0 out of the door? Master feels pretty good.

**Comment by drexin** [comment]
Yes, we plan to release an RC later today.

**Comment by sttts** [comment]
:+1:

**Comment by drexin** [comment]
@sttts Could you please squash this into a single commit?

**Comment by sttts** [comment]
Squashed the first 3. The 4th is kind of independent.

**Comment by drexin** [comment]
:100: Thanks!

**Pull request merged**
