### PR TITLE
Delete DC/OS cluster after system integration tests.

### PR DESCRIPTION
**Pull request by jeschkies**
Summary:
The clusters should be cleaned up but we do not want to wait for that to
happen.

### CODE REVIEW

**Comment by jeschkies** [comment]
I'll follow up for EE clusters once this works.

**Comment by jeschkies** [comment]
Check out the tests pipeline https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/system-integration-tests/job/marathon-si-dcos-open/job/karsten%252Fdelete-cluster/.

**Comment by zen-dog** [comment]
This is not necessarily this PR (but could be) - don't you want to add _dcos log bundle_ in finally? 
```
$ dcos node diagnostics create all
Job has been successfully started, available bundle: bundle-2017-10-17T13:27:55-295920586.zip

$ dcos node diagnostics --status
10.0.4.193
  command_exec_timeout_sec: 120
  diagnostics_bundle_dir: /var/lib/dcos/dcos-diagnostics/diag-bundles
  diagnostics_job_get_since_url_timeout_min: 2
  diagnostics_job_timeout_min: 720
  diagnostics_partition_disk_usage_percent: 1.5431300409520132
  errors: None
  is_running: False
  job_duration: 8.859179768s
  job_ended: 2017-10-17 13:28:04.155303972 +0000 UTC
  job_progress_percentage: 100
  job_started: 2017-10-17 13:27:55.296124429 +0000 UTC
  journald_logs_since_hours: 24h
  last_bundle_dir: /var/lib/dcos/dcos-diagnostics/diag-bundles/bundle-2017-10-17T13:27:55-295920586.zip
  status: Diagnostics job successfully finished

$ dcos node diagnostics download bundle-2017-10-17T13:27:55-295920586.zip
Diagnostics bundle downloaded to /.../bundle-2017-10-17T13:27:55-295920586.zip
```

**Comment by jeschkies** [comment]
The SI build passes. I will follow up with creating the diagnostic bundle.

**Pull request merged**
