### PR TITLE
Marathon Plugin Architecture

### PR DESCRIPTION
**Pull request by aquamatthias**
__DO NOT MERGE: it is meant as proposal__

## General idea
- identify functionality, where a service provider can be plugged in (extended or overridden)
- define a service provider interface for this functionality
- allow loading and using of service providers for the defined interface(s)

## marathon interface
Since the service provider needs some types to depend on, a separat sbt module has been created.
The marathon-interface is the library, a plugin depends on. With respect to marathon this should be the
only dependency (everything else is not considered as interface).

## event handling
The example extension of this proposal is to hook into the marathon event bus.
There are certain ideas to handle events, that should not be implemented in marathon directly (send events to a message queue etc.)

## example
See https://github.com/aquamatthias/marathon-test-plugin for an example plugin.

## implementation notes
The approach is based on the java service loader: https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html

@drexin @kolloch Feedback appreciated

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
+1 for the feature!

Java already provides a Service Provider Interface implementation, with established conventions and good docs.  Why not re-use it?  Here's an intro to how it works: https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html

From the user's perspective it's really easy to install new things (just add a JAR to the classpath).  From our end it's easy as well: query via the SPI library what implementations of a given interface (Scala trait) are available, choose one, get an instance.

**Comment by ConnorDoyle** [comment]
We should also make sure that people can write plugins in Java if they want to.

**Comment by hepin1989** [comment]
I have a better idea about this.
1,make the plugin trait not just a mark,but full lifecycle
```
trait Plugin[API >: Null <: AnyRef] {
  protected[plugin] def init(config: Config)

  def instance: API
}
```
then make the config from the 
```
marathon.plugin{
  plugin-a-config{
  }
}
```
then provide two annotation like 
```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Inherited
public @interface PluginConfigPath {
    String path() default "";
}
```
and 
```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@Inherited
public @interface Lazy {
}
```

the config path is used for loading the config,and the lazy is mark that should this plugin be lazy loaded.

then provide the plugin manager with the management of all the plugin's life cycle.

we may provide every plugin with a dedicated classloader.by this way we could reload the plugin with new version.

the config class here is using th typesafe-config.

**Comment by aquamatthias** [comment]
@ConnorDoyle this proposal is build on exactly that service provider contract that is available in Java for a long time (see implementation note and example). The service provider interface is `mesosphere.marathon.plugin.event.EventListener`. 

I think it should be perfectly possible, to implement the service provider in java. To ensure this, we could define the provider interface as pure java interface. 

@hepin1989 My first attempt was Plugin[API]. But that means no plain java SPI and additional burden for the Plugin developer. The ability to load/unload a plugin is not only the class loader reference. It needs a whole infrastructure and contract etc (e.g. osgi). With this proposal a new plugin can be reloaded by restarting marathon. 

Regarding configuration: marathon is configured via command line parameter. As a plugin developer you can use the config system of your choice (typesafe-config etc.). To pass config parameter, I suggest environment variables.

**Comment by kolloch** [comment]
@aquamatthias, I would like to close this for now if we do not plan to include this in the next releases. You can still reference it in associated issues.

**Pull request closed without merging**
