### PR TITLE
Fix GPU validation if 'container' isn't set. (#4224)

### PR DESCRIPTION
**Pull request by meichstedt**

### CODE REVIEW

**Comment by meichstedt** [comment]
@nfnt I cherry-picked the change to `releases/1.3` – needed to adjust this slightly but a review shouldn't take long and the tests passed locally.

**Comment by nfnt** [comment]
LGTM! 🚢

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
merged, thanks (=

**Pull request merged**
