### PR TITLE
Fake positive COMMAND health check results

### LINKED ISSUE #916: Command health checks do not survive Marathon restart
Create an app with a COMMAND health checks. When the app turns healthy, restart Marathon (probably a leader change will also be sufficient). The app will stay grey. 

The Mesos COMMAND health check is still running at this point because its output is visible in the task's stdout/err, but Marathon does not see the health check results anymore.

### PR DESCRIPTION
**Pull request by sttts**
Mesos reports positive health checks only once. If Marathon has taken over
leadership after a COMMAND check task was started, it will never see the
positive health check result. Hence, we fake it, assuming that a COMMAND
health check is positive if no negative result is received after a long
enough time.

Fixes #916.

### CODE REVIEW

**Comment by sttts** [comment]
@ConnorDoyle if you need help with the Mesos patch, just tell me.

**Comment by ConnorDoyle** [comment]
Thanks for the offer to help out @sttts. The JIRA is here: [MESOS-2206](https://issues.apache.org/jira/browse/MESOS-2206).  Dug a little deeper and found out that the healthy field is simply not set during reconciliation (re-registration triggers implicit reconciliation).  Should have a review up today or tomorrow.  As usual, the tests are bigger than the actual fix :wink:.

**Comment by ConnorDoyle** [comment]
Closing this, as the issue has been resolved in Mesos.  See also #963, which reduces the initial task reconciliation delay.

**Comment by sttts** [comment]
Very good!

**Pull request closed without merging**
