### PR TITLE
Add replicated log storage provider

### PR DESCRIPTION
**Pull request by aquamatthias**
based on master

### CODE REVIEW

**Comment by kolloch** [comment]
Can we close that?

**Comment by aquamatthias** [comment]
This is based on master - I hope it makes sense there as well.

**Comment by cmaloney** [comment]
Should look at: https://youtu.be/ZQenXkoG_7o for lots of good insights around this (Case Study of Apache Aurora implementing/using the mesos replicated log)

**Comment by stephentknight** [comment]
Will this assist in recovery of Docker machines to their previous state? I understand it aids in recovery of applications (is that correct), since Docker is considered first class, will this mean that in the event of an unexpected reboot I can recover my stateful Docker container deployed via Marathon?

**Comment by kolloch** [comment]
@stephentknight This PR is only related to the state kept directly by Marathon: The App Definitions, Groups, Running Tasks. What you suggest would require Mesos/Docker support.

**Comment by kolloch** [comment]
Since this PR is not mergeable and I do not see progress, I close this PR for now.

Please feel very free to reopen with an updated PR!

**Pull request closed without merging**
