### PR TITLE
[WIP] debugging flaky KillServiceActorTest

### PR DESCRIPTION
**Pull request by meichstedt**
extended debugging to find flakiness

### CODE REVIEW

**Comment by meichstedt** [comment]
retest this please

**Comment by meichstedt** [comment]
retest this please

**Comment by meichstedt** [comment]
retest this please

**Comment by aquamatthias** [comment]
@meichstedt is that still open? (is there a phabricator review?)

**Comment by meichstedt** [comment]
wasn't aware of this at all. I'll try to apply this to the current master and will create a diff when it works and still makes sense (it's nearly 2 months old ..)

**Pull request closed without merging**
