### PR TITLE
Fixes #3139 - Do not restart unchanged apps

### LINKED ISSUE #3139: Marathon 0.15.0-1.0.457.ubuntu1404 forces redeploy of app all the time
Scenario:

- Ubuntu `14.04`
- Mesos `0.27.0-0.2.190.ubuntu1404`
- Marathon `0.15.0-1.0.457.ubuntu1404`

On Marathon `0.14.1-1.0.455.ubuntu1404`, when you deploy/update an app without any changes in the JSON, no deployment happen:

1. `curl -XPUT -i -H 'Content-Type: application/json' -d @test.json marathon.example.com:8080/v2/apps/test`
1. deployment happen
1. update app again with **no changes in JSON** `curl -XPUT -i -H 'Content-Type: application/json' -d @test.json marathon.example.com:8080/v2/apps/test`
1. **no** deployment happen

But when using Marathon `0.15.0-1.0.457.ubuntu1404`, deployment happen all the time:

1. `curl -XPUT -i -H 'Content-Type: application/json' -d @test.json marathon.example.com:8080/v2/apps/test`
1. deployment happen
1. update app again with **no changes in JSON** `curl -XPUT -i -H 'Content-Type: application/json' -d @test.json marathon.example.com:8080/v2/apps/test`
1. **deployment happen**

We reverted back to 0.14.1 in meantime and it's now working as intended.

### PR DESCRIPTION
**Pull request by kolloch**
Cherry-pick to release branch after merge!

I will check if I can also write an integration test for this quickly but I'd already appreciate feedback.

### CODE REVIEW

**Comment by gkleiman** [comment]
LGTM

**Comment by kolloch** [comment]
added an integration test as well

**Comment by meichstedt** [comment]
LGTM too – waiting for tests

**Comment by meichstedt** [comment]
cherry-picked onto `releases/0.15`

**Pull request merged**
