### PR TITLE
Adding relative time in stead of version labels

### PR DESCRIPTION
**Pull request by mlunoe**
Fixes issue https://github.com/mesosphere/marathon/issues/1025

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Could you post some before / after screenshots?

**Comment by mlunoe** [comment]
Yes, just out for a moment. Will do when I get back

**Comment by mlunoe** [comment]
Before:
before

After:
after

**Comment by bobrik** [comment]
@mlunoe, I wonder if you really wanted to add 50k lines of compiled js in this PR.

Is it possible to see which tasks belong to new/old version of an app during deployment?

**Comment by mlunoe** [comment]
Woops! Accidentally committed the development version in stead of the production. Should be fixed now.

And yes, it is possible. You can see the relative time show a more recent version. And if you hover over the task you can get the exact version number (ISO date).

**Comment by aldipower** [comment]
:thumbsup:

**Comment by drexin** [comment]
:100:

**Pull request merged**
