### PR TITLE
WIP: ZooKeeper digest authentication support

### PR DESCRIPTION
**Pull request by sttts**
Based on #3777
Follow-up of #3096 

- [x] use correct ACL
- [x] integration test
- [x] rebase onto master as soon as #3777 is merged

### CODE REVIEW

**Comment by aquamatthias** [comment]
@sttts Thanks. LGTM!
Will wait for the other PR to get merged.

**Comment by aquamatthias** [comment]
@sttts please rebase

**Comment by sttts** [comment]
Rebase done. You can merge when tests are green.

**Comment by aquamatthias** [comment]
Thanks!!

**Pull request merged**
