### PR TITLE
adding HTTPS support

### PR DESCRIPTION
**Pull request by nevins-b**
Replacement for #956 correctly rebased.

### CODE REVIEW

**Comment by drexin** [comment]
@nevins-b Could you please check the compile error?

**Comment by nevins-b** [comment]
@drexin Looks better now.

**Comment by drexin** [comment]
Yep, please squash it into a single commit again. Btw. no need for a new PR, just squash it and force push it to your branch.

**Comment by nevins-b** [comment]
@drexin yeah, my previous pull request I had rebased before so I couldn't squash.

**Comment by drexin** [comment]
I see, thanks!

**Comment by drexin** [comment]
:100: Thanks!

**Pull request merged**
