### PR TITLE
Use CurrentRuntime.async for killing the current process.

### PR DESCRIPTION
**Pull request by aquamatthias**

### CODE REVIEW

**Comment by jasongilanfarr** [comment]
LGTM

**Comment by gkleiman** [comment]
LGTM

Note: this change makes Marathon wait 10 seconds instead of 5 before doing the halt.

**Comment by meichstedt** [comment]
@gkleiman yes, that was intentionally aligned

**Comment by meichstedt** [comment]
Thanks @aquamatthias

**Pull request merged**
