### PR TITLE
back port curator leader election to 1.1 release track

### PR DESCRIPTION
**Pull request by unterstein**
Includes cherry picks for:
- Usage of curator for leader election
- Reverting  `Implementation of virtual heartbeat monitor to help detect network` adaptions for release 1.1 branch and re-applying original patch

### CODE REVIEW

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
`Test Result (no failures)`

**Comment by unterstein** [comment]
retest this please

**Comment by aquamatthias** [comment]
@unterstein Thanks. I will close this PR until there is an urgent need to backport the election service.

**Pull request closed without merging**
