### PR TITLE
Su/external vol doc fix

### PR DESCRIPTION
**Pull request by sascala**
@jdef I fixed the bug you mentioned here: https://github.com/mesosphere/marathon/pull/3715/commits/c548994473215dfe5e82fcb595cbd12ff0efa3f2#r59308860

**NOTE:** Blocked from merge to master, waiting on #3832

### CODE REVIEW

**Comment by jdef** [comment]
thanks @sascala, that change looks good. re-assigning back to you

**Comment by aquamatthias** [comment]
@sascala what is the status of this PR? Can it be merged? It definitively needs a rebase.

**Comment by sascala** [comment]
I stopped work on this when it turned out external volume wouldn't ship with 1.7. I'll close the PR and reopen when external volumes are ready to go.

**Comment by sascala** [comment]
This PR has a bunch of changes that are now irrelevant. Closing, and I'll open another that's up-to-date.

**Pull request closed without merging**
