### PR TITLE
fixes #1106 - Return empty HealthCheck result instead of None, when no r...

### LINKED ISSUE #1106: Health check result array [null] returned in embedded tasks sometimes
Might be related to #1082.

### PR DESCRIPTION
**Pull request by drexin**
...esults are present

### CODE REVIEW

**Comment by sttts** [comment]
Doesn't this change the semantics of the "alive" value of the health check result? When a task has not received any health result with this patch, the /apps endpoint will return a health check result with alive=true, won't it?

**Comment by sttts** [comment]
In other words, we either have the Option[Health] type or we have to change the type of alive from Boolean to Option[Boolean].

**Comment by bobrik** [comment]
Related to #940 too.

**Comment by drexin** [comment]
@sttts You're right. Closing this until I find a better solution.

**Comment by drexin** [comment]
Hm... Actually if it doesn't have a `lastFailure` set, you can be sure that it has never been healthy, so setting `healthy = false` should be okay.

**Comment by sttts** [comment]
Only alive is misleading. In the json we can set alive=null, in the code alive: Option[Boolean].

**Comment by drexin** [comment]
`alive = false` is correct, because it has never been alive. I think `firstFailure = null` should be enough to determine that it just didn't fully start yet.

**Comment by sttts** [comment]
Got what you mean. alive=false is better than healthy=false.

**Comment by sttts** [comment]
What is the opinion here?

My feeling is that the new semantics of alive=false + lastFailure=null is a bit complicated, but makes sense on the second thought.

**Comment by drexin** [comment]
@ConnorDoyle Could you please review?

**Pull request merged**
