### PR TITLE
Ignore health checks with HTTP response 100 to 199

### LINKED ISSUE #1126: Variable grace period – supporting HTTP health check result "100 - continue"
To be able to run a distributed database like MySQL Galera in a Mesos cluster, it is necessary to support an initial replication phase. In this phase the task is neither healthy (= ready to answer external requests) nor unhealthy (= something is wrong). It's similar to the grace period in Marathon, but we don't know how long it will take. In addition the health check knows when this initial replication phase is finished and when it fails.

The idea for such a scenario is to add a third HTTP status case:

- 100 continue => ignore this health check interval for the given task
- 200-399 => task is healthy
- >400 => task is unhealthy.

### PR DESCRIPTION
**Pull request by sttts**
To support apps which have a variable startup time, having only healthy and
unhealthy as results of health checks is not enough. This patch introduces
a third behaviour for the HTTP response codes 100 to 199: health checks with
these response codes are ignored.

Fixes #1126

### CODE REVIEW

**Comment by drexin** [comment]
Can we make the range of ignored status codes configurable like the range of succes codes?

**Comment by sttts** [comment]
Sure. Didn't know it's possible for the healthy codes.

**Comment by drexin** [comment]
@sttts Oh, sorry. Seems like that's not true anymore. But let's make it optional then.

**Comment by sttts** [comment]
"ignoreLowHttpResponses: true" ? Something in this direction?

**Comment by drexin** [comment]
1xx codes are called "Informational", so maybe something like `ignoreInformationalResponses`.

**Comment by drexin** [comment]
Or `ignoreInformationalStatus`

**Comment by sttts** [comment]
As it only applies to Http checks, I would add that to the name.

**Comment by drexin** [comment]
Right.

**Comment by sttts** [comment]
ignoreHttpInformationalStatus. long word.

**Comment by sttts** [comment]
ignoreHttp1xx

**Comment by drexin** [comment]
Let's go with that if @ConnorDoyle agrees ;-)

**Comment by sttts** [comment]
`ignoreHttp1xx` gives ugly `ignoreHttp1Xx` via protobuf. Alternative: `ignoreHttp100to199`.

**Comment by drexin** [comment]
@sttts Could you please also add this to the changelog_0.8.0-0.8.1.md?

**Comment by sttts** [comment]
Where is that changelog_0.8.0-0.8.1.md?

**Comment by bobrik** [comment]
Is there a reason to have a separate file for every version? I think one changelog to rule them all is more common practice. People tend to skip several versions and reading several files is not very convenient.

@sttts see https://github.com/mesosphere/marathon/tree/master/changelogs

**Comment by drexin** [comment]
Could you please rebase and squash this PR and add the new setting to the changelog?

**Comment by sttts** [comment]
Squashed and rebased.

Wondering about the changelog: these patches always make the PRs unmergable. How about requiring to write a changelog entry into the PR message and collect those on release from github?

**Comment by drexin** [comment]
:100: Thanks a lot!

I think we should keep the changelog file, it would be really cumbersome the assemble all the changes for a bigger release.

**Comment by drexin** [comment]
Not sure why it leads to conflicts, though.

**Comment by sttts** [comment]
But if you are really consequent with the changelog changes in each PR, you will get tons of conflicts and rebases before merging.

**Comment by drexin** [comment]
Only visible changes should be tracked there. Like changes in the API, new endpoints etc. Bug fixes don't have to be mentioned there.

**Pull request merged**
