### PR TITLE
Fixes #3266 by introducing an optional precedence (PathId) for OfferMatchers.

### LINKED ISSUE #3232: Resident Tasks: Treat status updates correctly
Task status updates should be treated correctly. Probably similar to the following:

On termination, remove the "launch" information from the task. If the task has a reservation, keep it, otherwise delete it.

### LINKED ISSUE #3266: Resident Tasks: offer matching priority should keep reserved resources into account
The OfferMatcherManager handles all OfferMatcher equally.
If we find a reserved resource, we can directly give the offer that offer matcher.

### PR DESCRIPTION
**Pull request by aquamatthias**
If defined and an offer arrives with a reserved volume that matches the criteria, the matcher gets the offer first.

### CODE REVIEW

**Comment by meichstedt** [comment]
Beautiful :tulip: – I'm merely missing a test for it!

**Comment by aquamatthias** [comment]
@meichstedt Added a test case for this functionality.

**Comment by meichstedt** [comment]
Nice, thanks for the test! Please squash!

**Comment by aquamatthias** [comment]
Squashed.

**Comment by meichstedt** [comment]
```
          (`-,-,
           ('(_,( )
            _   `_'
         __|_|__|_|_
       _|___________|__
      |o o o o o o o o/ 
     ~'`~'`~'`~'`~'`~'`~
```

**Comment by aquamatthias** [comment]
Thanks for the nice ship!

**Pull request merged**
