### PR TITLE
Fixes #3694 by enabling chaos gzip handling.

### LINKED ISSUE #3694: Configure Jetty to serve gzipped static assets
Marathon currently serves static assets with no gzip compression. When turned on this would reduce the download size to ~1/4 of the total size. (currently `main.js` measures `1.8m` and `514k` when gzipped).

It should be easily possible to implement gzip for static content  by setting an initParameter `gzip = true`, apparently: http://download.eclipse.org/jetty/9.3.7.v20160115/apidocs/org/eclipse/jetty/servlet/DefaultServlet.html

I would open a PR myself but my Java fails me.

### PR DESCRIPTION
**Pull request by aquamatthias**
- use chaos 0.8.5 with gzip handling
- add http_compression flag
- bump version of scallop to 1.0
- deprecate asset_path property

### CODE REVIEW

**Comment by aquamatthias** [comment]
@gkleiman before merging, we need to merge and release this: https://github.com/mesosphere/chaos/pull/67

**Comment by gkleiman** [comment]
@aquamatthias Should we do a new Chaos release now that https://github.com/mesosphere/chaos/pull/67 is merged?

**Comment by aquamatthias** [comment]
Already done and PR updated.

**Comment by gkleiman** [comment]
@aquamatthias great, thanks!

Can you please squash and update Chaos' version number in the commit description?

**Comment by aquamatthias** [comment]
@gkleiman done

**Comment by gkleiman** [comment]
Merged, thanks!

**Pull request merged**
