### PR TITLE
Fixes #3957 - Load previously stored health status when becoming leader

### LINKED ISSUE #3957: COMMAND HealthChecks removed on mesos-master restart/issue
COMMAND Health Checks are being removed (i.e. `INFO Removing health check for app`) and never re-created when something happens to the mesos-master. I have seen this with both a restart of the mesos-master and also under less controlled situations such as a leader re-election or network issues.

To reproduce:

1) Create an App with a COMMAND Health Check
2) Restart mesos-master
3) grep marathon log for `Removing health check`

Although `addAllFor` and subsequently `add` is called (which you can see int he logs: `INFO Adding health check for app`) No health check data is ever available either via the UI (the good old grey bar of doom) or via the JSON return via the API.

The HTTP and TCP Health Checks return successfully but the only way to re-establish the COMMAND Health Checks is to restart the Apps.

Using:
Mesos: 0.28.0
Marathon: 1.1.1

### PR DESCRIPTION
**Pull request by gkleiman**
(cherry picked from commit 25c59df10fb4d6ee941c8289a2ad4904332dde79)

### CODE REVIEW

**Comment by aquamatthias** [comment]
retest this please

**Comment by aquamatthias** [comment]
LGTM - ship it.
@jeschkies This build fails in Velocity. Can you try to make the build green? Thanks

**Comment by jeschkies** [comment]
retest this please

**Comment by jeschkies** [comment]
retest this please

**Comment by jeschkies** [comment]
retest this please

**Pull request merged**
