### PR TITLE
[WIP] Remove JSON Schema in favor of RAML

### PR DESCRIPTION
**Pull request by timcharper**
JIRA issues: MARATHON-7978

### CODE REVIEW

**Comment by timcharper** [comment]
@jdef anything else of which you're aware that we need to do for this?

**Comment by jdef** [comment]
isn't there a unit test (or more than one) that attempts to load the schema file and test various properties?

**Comment by jdef** [comment]
for example: https://github.com/mesosphere/marathon/blob/15e85e5f30c549aa975ac852597cef9de00daa67/src/test/scala/mesosphere/marathon/api/v2/json/AppDefinitionSchemaJSONTest.scala

**Comment by jdef** [comment]
some things to double-check:
- [ ] DC/OS CLI dependency on schema (if any)
- [ ] DC/OS UI dependency on schema (if any)
- [ ] Marathon Java Client dependency on schema (if any)

**Comment by jdef** [comment]
To which endpoint are you referring?

On Wed, Dec 20, 2017 at 8:28 AM, Karsten Jeschkies <notifications@github.com

**Comment by meln1k** [comment]
I agree with @jeschkies regarding the backwards compatibility.

**Comment by meichstedt** [comment]
I agree that removing the endpoint and the schemas should be considered a breaking change, we don't know who's relying on it. We could mitigate that by redirecting to the 1.5 content on GH? 😬 

However, the raml is the source of truth and AFAIK we don't even have tests that verify the compatibility between the two, so it is also questionable how much value the endpoint and the schema are actually providing.

**Comment by timcharper** [comment]
Yes, I had all of the same concerns. It's doubtful that it is being used. In the JIRA I raised this question.

After sleeping on it for a night I feel worse about it. We should deprecate the endpoint with a flag, and then remove in a subsequent major version.

**Comment by timcharper** [comment]
I have a follow up PR that uses the newly introduced deprecation mechanism, which will allow us to phase this out more gracefully:

https://github.com/mesosphere/marathon/pull/6280

**Pull request closed without merging**
