### PR TITLE
Workaround added concerning the Docker issue with external volumes.

### PR DESCRIPTION
**Pull request by ArmandGrillet**
The solution is to use a Mesos container with a Docker image, it gives
the ability to use a Docker image while preventing the automatic
creation of anonymous volumes.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4804" target="_blank">ReviewNinja

**Comment by lloesche** [comment]
I think I would remove the `thanks to the Mesos containerizer` part and just leave the fact that the issue doesn't arise using the Mesos containerizer.
I love the Mesos containerizer as much as the next guy but given it's our own documentation it might sound a bit pompous. 😄 

Other than that 👍  :shipit:

**Comment by aquamatthias** [comment]
Thanks @ArmandGrillet. Please change the sentence according to Lukas suggestion.

**Comment by aquamatthias** [comment]
@ArmandGrillet Thanks!

**Pull request merged**
