### PR TITLE
Add Authenticator test for "not authenticated" case

### PR DESCRIPTION
**Pull request by redshirtrob**
Also fixed wording in the "authenticated" test case.

### CODE REVIEW

**Comment by timcharper** [comment]
lgtm, thanks!

**Comment by timcharper** [comment]
ok to test

**Comment by unterstein** [comment]
lgtm thanks. Will trigger CI with my next comment

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
retest this please

**Comment by redshirtrob** [comment]
@timcharper @unterstein Any chance this will get merged?

**Comment by unterstein** [comment]
sure, would love to!

Would it be possible to rebase this branch on the latest master to re-trigger ci?

Thank you

**Pull request merged**
