### PR TITLE
Add Google HTML verification file

### PR DESCRIPTION
**Pull request by joel-hamill**
Add google HTML verification file. This allows us to ask Google to index the marathon docs site. 

- https://jira.mesosphere.com/browse/DOCS-1795

### CODE REVIEW

**Comment by joel-hamill** [comment]
CC @sascala @surdy

**Comment by surdy** [comment]
Awesome !! Thanks @joel-hamill

**Comment by aquamatthias** [comment]
Thanks!

**Comment by aquamatthias** [comment]
@joel-hamill cherry picked on release branch. Merged with gh-pages.
This page is now available under: https://mesosphere.github.io/marathon/google6dc7450c38e56aed.html

**Pull request merged**
