### PR TITLE
changing nodce requirements

### PR DESCRIPTION
**Pull request by mlunoe**

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Related to #1017.

**Comment by ConnorDoyle** [comment]
Could you disable the frontend style warnings for now?  Maybe turn them back on after you've applied the style fixes on top of the new build system.  It's currently so verbose that Travis refuses to display the build logs.

**Comment by mlunoe** [comment]
I will turn them off

**Comment by ConnorDoyle** [comment]
Please wait for a :shipit: before self-merging in the future.

**Comment by mlunoe** [comment]
Sorry, I thought we agreed. Will wait in the future

**Pull request merged**
