### PR TITLE
Add link to Slack and minor  grammatical edits.

### PR DESCRIPTION
**Pull request by ssk2**
Add link to Slack and minor  grammatical edits.

Summary:
Added a link to the Mesos Slack.

JIRA issues:
N/A

### CODE REVIEW

**Comment by ssk2** [comment]
FYI, both the test results and logs seem to require authentication (is this by design? rename the build with `public-` for the results to be made publicly viewable).

**Comment by alenkacz** [comment]
@ssk2 and thank's for pointing out that jenkins login thing. I'll look into it today...

**Comment by kensipe** [comment]
hey @ssk2 always great to see you name come up!    hope all is well with you and your new team.

**Comment by alenkacz** [comment]
@ssk2 the build should now be publicly available. Thanks for pointing it out...

**Comment by ssk2** [comment]
Thank you @alenkacz!

**Pull request merged**
