### PR TITLE
Mention --mesos_authentication Marathon flag.

### PR DESCRIPTION
**Pull request by mjkelly**
I found no mention of this flag in any documentation. Based on my experience, Marathon 1.3 does not attempt to authenticate at all unless this flag is set.

Let me know if I should add this in other places as well.

### CODE REVIEW

**Comment by aquamatthias** [comment]
test this please

**Comment by aquamatthias** [comment]
ok to test

**Comment by jasongilanfarr** [comment]
@zen-dog The test comments are us approving it to go through CI

**Comment by mjkelly** [comment]
Re-merged master (via the GH button).

**Comment by jdef** [comment]
test this please

**Comment by jdef** [comment]
test flake #4559

**Comment by jasongilanfarr** [comment]
Don't worry about this for a minute, I'll manually override and merge.
We're about 30minutes from landing a major feature branch.

**Pull request merged**
