### PR TITLE
Replace custom stage with newly introduced akka flow op zipLatestWith

### PR DESCRIPTION
**Pull request by timcharper**
Akka has recently added the flow operator zipLatestWith, which matches the behavior of CombineLatest.

### CODE REVIEW

**Comment by timcharper** [comment]
This component was already removed from 1.8 and later. ¯\_(ツ)_/¯

**Comment by timcharper** [comment]
Follow up to https://github.com/mesosphere/marathon/pull/6949

**Comment by ANeumann82** [comment]
Soooo... The component was removed in 1.8 and later. Should we really update the akka version in a 1.7.x patch release? I mean, it's nice to remove code, but maybe we should just leave it in 1.7 as is?

**Comment by timcharper** [comment]
Yeah, on second thought, I think so too.

**Pull request closed without merging**
