### PR TITLE
Add custom resource feature and more

### PR DESCRIPTION
**Pull request by cinsk**
AFAIK, Marathon only handles predefined resources (i.e. "cpus", "mem", "disk", "ports").  While this satisfies most of user's need, it may not suffcient for certain environments.

This branch adds several enhancements like:

- ability to add custom resources on launching/updating apps
- ability to handle heterogeneous resource matching (e.g. request `ScalarResource` for `SetResource`, etc.)
- ability to use regular expression on `SetResource` matching,
- ability to specify a simple conditional constraints on regular expression matching.

For the explanation, assume that we have only one mesos-slave with following resources:

    ScalarResource("cpus", 10)
    ScalarResource("mem", 100)
    // "disk" refers to the shared storage, network attached, with large amount of space.
    ScalarResource("disk", 10000)
    // "gpu" referes to the graphic cards locally attached.
    SetResource("gpu", Set("gpu-1", "gpu-2", "gpu-3", "gpu-4"))
    // "ephermeral" refers to the local storage, for ephemeal purpose.
    SetResource("ephemeral", Set("sdd-10", "hdd-100", "sdd-100", "hdd-80"))

Now, if the application needs exactly "gpu-1" and "gpu-3", the user can `POST /v2/apps` using

    {
        "id": "/product/service/my-app",
        "cmd": "env && sleep 300",
        "args": ["/bin/sh", "-c", "env && sleep 300"],
        "resources": [ { "name": "gpu",
                         "value": [ "gpu-1", "gpu-3" ] } ],
        ...
    }

However, if the user just want to use two GPUs, then he or she can use following JSON request:

    {
        "id": ...,
        "cmd": ...,
        "resources": [ { "name": "gpu",
                         "value": 2 } ],
        ...
    }

To match `SetResource` request to `SetResource` offer, you may use a regular expression pattern.   A string in `SetResource` request may have the form `"#N;CONSTRAINT#PATTERN"`, where `N` is the number of resource requesting, `CONSTRAINT` is an optional simple Java-like expression to restrict the matching, and `PATTERN` is the regular expression to match against the offer.

Assume that the app needs two `hdd`s from "ephemeral" resource.  Then the user may specify `"#2#hdd-.*"` like this:

    {
        "id": ...,
        "cmd": ...,
        "resources": [ { "name": "ephemeral",
                         "value": [ "#2#hdd-.*" ] } ],
         ...
    }

Assume that the app needs two ephermerals, and the user does not care whether they are `hdd`s or `sdd`s, but the user wants them larger than 99.  Then the user may specify `"#2;m[1]>99#[sh]dd-(.*)"` like this:

    {
        "id": ...,
        "cmd": ...,
        "resources": [ { "name": "ephemeral",
                         "value": [ "#2;m[1]>99#[sh]dd-(.*)" ] } ],
         ...
    }

Note that there are a few restrictions on the `CONSTRAINT`:

- the conditional expression can only deal with number(double) and boolean.
- If the regular expression has subgroups, you may refer them as `m[1]`, `m[2]`, and so on.
- It provides most conditional expression and comparison operators such as `>`, `<`, `>=`, `<=`, `==`, `!=`, `&&`, `||` in addition to `+`, `-`, `*`, `/`, `()`.

Thank you,

### CODE REVIEW

**Comment by iahmedkaseb** [comment]
Hi @cinsk,

I am interested in the feature of custom resource types. I have a couple of questions:

1- Is the feature working or still in development?
2- Are there any news about merging this pull request into Marathon?
3- You added multiple features in this pull request. Is the first commit the only one related to custom resource types? Or are the other commits needed as well?

Thank you.

**Comment by cinsk** [comment]
Hi, Ahmed Kaseb.

Answer of Q1:  In the marathon code base, this is working. (not fully tested though)

However, to support custom resource, we need more work.  This patch is a custom resource support on the scheduling-side (i.e. Marathon source tree).   We also need to implement/update executor-side (i.e. Mesos source tree).   In details, this handles custom resource matching in TaskBuilder class, then pass the allocated resource via an environment variable, `AUX_RESOURCES`. In the executor side (Mesos executor, or other custom executor), the executor should aware of this `AUX_RESOURCES` variable, and deal with it so that the task application can understand the custom resources.  Especially, if the task runs in docker container, the executor should build docker command-line with `--device` option.

Answer of Q2

Since our team uses our own custom framework/executor, we have not tested fully. However, if the Marathon team has interest to support this feature, we are willing to continue to work on this.  As I explained in above, we need custom resource support on executor side.  So are you going to use mesos executor as before?  In that case we need to patch mesos code base.

Answer of Q3

The whole 4 commit are needed (2 for major update, others are minors however.)

**Comment by aquamatthias** [comment]
Thanks for this PR! We will try to look into this and see where it will fit.

**Comment by kolloch** [comment]
Hi @cinsk, thank you very much for your PR. Unfortunately, we are not ready quite yet. See the discussion in https://github.com/mesosphere/marathon/issues/375. After agreeing on an API format, I would like to move ahead with a PR focussing on scalar custom resources only.

**Pull request closed without merging**
