### PR TITLE
Updated changelog for 1.2

### PR DESCRIPTION
**Pull request by liyubobj**

### CODE REVIEW

**Comment by aquamatthias** [comment]
@liyubobj Thanks for this update. We have feature freeze for Marathon 1.2. That is why a Marathon 1.3 release branch was cut, which has the unified containerizer and GPU support. 
This should be reflected in the changelog as well.

**Comment by liyubobj** [comment]
I see. Shall I update this change-log to 1.3 or you will work on it? @aquamatthias

**Comment by unterstein** [comment]
Hi @liyubobj,

sorry for the delay! I recently adapted the changelog to adapt 1.3 (we are skipping 1.2 as final release) and after this PR is merged, it would be super cool, if you could rebase your change on master and then I will merge this :)

Thanks
Johannes

**Comment by liyubobj** [comment]
Code rebased @unterstein , please let me know if anything need to be revised. Thanks!

**Comment by unterstein** [comment]
Hi @liyubobj, I am afraid you were a little bit too fast :) It would be super awesome if you could do another rebase

**Comment by liyubobj** [comment]
Sure, rebased :)

**Comment by unterstein** [comment]
retest this please

**Comment by liyubobj** [comment]
Can it be merged?

**Comment by unterstein** [comment]
I would like to, but CI fails ... I`ll try to trigger a retest.

**Comment by unterstein** [comment]
retest this please

**Comment by liyubobj** [comment]
I triggered a re-test by `git commit --amend`. Is that what you want me do?

**Comment by unterstein** [comment]
Ah no, `retest this please` is a hook to trigger the testing :D

**Comment by liyubobj** [comment]
OK, I see...

**Comment by unterstein** [comment]
🚢

merged, thanks :-)

**Pull request merged**
