### PR TITLE
Log incoming offers at info level

### PR DESCRIPTION
**Pull request by meln1k**
Summary: added info logging of incoming offers

JIRA issues: MARATHON-8282

(cherry picked from commit 38cb286)

### CODE REVIEW

**Comment by timcharper** [comment]
I missed the review of the first commit, but was the intention was to do "one-liners" per the conversation in MARATHON-8282? And, if so, by one-liners, I thought "offer summary". It looks like here we are serializing the whole offer? This seems potentially pretty lengthy.

**Comment by meln1k** [comment]
@timcharper thanks for the suggestion. I'll update the master branch and backport again :)

**Comment by jeschkies** [comment]
Is on `releases/1.6` already or do we need a backport for that?

**Comment by meln1k** [comment]
@jeschkies 1.6 has it, we need to backport to 1.5

**Pull request merged**
