### PR TITLE
Run Integration tests in velocity

### PR DESCRIPTION
**Pull request by jasongilanfarr**

### CODE REVIEW

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
One test fails in Velocity (docker in docker in docker probably doesn't work all that well):
mesosphere.marathon.integration.setup.DockerAppIntegrationTest.create a simple docker app using http health checks with HOST networking

I'm adjusting detection of "RUN_DOCKER_INTEGRATION_TESTS" to set this to false if its in Velocity.

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
Retest this please

**Comment by jdef** [comment]
lgtm once tests pass

**Pull request merged**
