### PR TITLE
Add link to Jira

### PR DESCRIPTION
**Pull request by meichstedt**

### CODE REVIEW

**Comment by marcomonaco** [comment]
lgtm

**Comment by jdef** [comment]
The "issues" tab used to be up top, easy to find and search. This JIRA link is embedded in a paragraph of text. Not easy to find. Can we move this to the top of the README, or perhaps to the summary line at the top of the project page on GH?

**Comment by janisz** [comment]
I agree with @jdef Maybe some badge on a top of readme https://shields.io/?

**Comment by meichstedt** [comment]
Thanks for your suggestions, @jdef and @janisz 
I'm happy to remove one or both in-text links now that the badge is linked – what do you think?

**Comment by jdef** [comment]
much better, thanks. small suggestion: reverse the order of issues/jira and make the color more mesosphere, like this?
```md
[![Issues](https://img.shields.io/badge/Issues-JIRA-ff69b4.svg?style=flat)](https://jira.mesosphere.com/projects/MARATHON/issues/)
```

**Pull request merged**
