### PR TITLE
fixes #801 - Send webui_url in FrameworkInfo

### LINKED ISSUE #801: Send `webui_url` in FrameworkInfo
New in Mesos 0.21.0.
See: https://github.com/apache/mesos/blob/0.21.0/include/mesos/mesos.proto#L131

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

**Comment by aquamatthias** [comment]
:ship: it.

**Comment by bobrik** [comment]
Hm, I wonder how many people set up reverse proxy in front of marathon servers. I use internal IPs to create tasks with API, but developers usually use proxy that only allows GET requests, does https termination and has well-known external domain.

What do you think about making webui url configurable as cli flag?

**Comment by aquamatthias** [comment]
You can set the advertised hostname via --hostname and the port via --http_port or --https_port.

**Comment by bobrik** [comment]
`--hostname` is different.

Imagine running 3 marathon servers: `marathon1.local`, `marathon2.local`, `marathon3.local`. They are only accessible on internal network. Now I want to run `marathon.example.com` in read-only mode for everyone with access to vpn network and with basic auth for those who want to use `marathon.example.com` with ability to scale/stop deploys/create apps.

In mesos ui I want to use `marathon.example.com`.

**Comment by drexin** [comment]
Good idea. I created a ticket here: https://github.com/mesosphere/marathon/issues/1231

**Pull request merged**
