### PR TITLE
810 Get rid of the Modal/lightbox

### PR DESCRIPTION
**Pull request by aldipower**
Get rid of the Modal/lightbox - relating to issue https://github.com/mesosphere/marathon/issues/810

Introducing a PageComponent inherit from the ModelComponent functionality.
The header css still has to be styled.

### CODE REVIEW

**Comment by drexin** [comment]
@aldipower Can we also close this?

**Comment by aldipower** [comment]
Yes, please, thanx.

Am 12.01.2015 um 18:19 schrieb Dario Rexin:

**Comment by mlunoe** [comment]
@aldipower Are you going to start over with this as well?

**Comment by aldipower** [comment]
Correct. :)

Am 12.01.2015 um 19:58 schrieb Michael Lunøe:

**Pull request closed without merging**
