### PR TITLE
#2426 get rid of v2 model objects

### PR DESCRIPTION
**Pull request by alexanderweber**
Using play-json, we are no longer in need for `V2AppDefinition` or `V2Group` classes anymore. This pull request should get rid of those classes.

### CODE REVIEW

**Comment by aquamatthias** [comment]
@alexanderweber this branch has everything that is in the ModelValidation branch - correct? You can create a branch on top of another branch. That way we see only the changes for Model Objects.

**Comment by alexanderweber** [comment]
@aquamatthias you are right. Should I close this one and open a new pull request having the ModelValidation replacement as base?

**Comment by aquamatthias** [comment]
Yes please.

**Comment by alexanderweber** [comment]
New pull request created: #2837

**Pull request closed without merging**
