### PR TITLE
Revert "Mark unstable tests"

### PR DESCRIPTION
**Pull request by unterstein**
This reverts commit a509790c9306432fa2ee6159960525af073faf3f.

Let`s mark them stable again for `releases/1.4` <3

### CODE REVIEW

**Comment by jdef** [comment]
they're being marked stable because ... some other recent commits fix them? (if so, care to xref?)

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
@jdef `Mark as unstable` commit should not have been landed on releases/1.4 via cherry-picks.

**Comment by jdef** [comment]
ok, sgtm

**Comment by unterstein** [comment]
it green

**Comment by unterstein** [comment]
retest this please

**Comment by aquamatthias** [comment]
retest this please

**Comment by unterstein** [comment]
it green - running it again

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
it green - running it again

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
retest this please

**Comment by jeschkies** [comment]
I've checked. The test simply timed out.

**Comment by aquamatthias** [comment]
Thanks!

**Pull request merged**
