### PR TITLE
fixes #347 - Disable http caching by default

### LINKED ISSUE #347: IE9 uses cached Ajax responses, never updates /v2/apps
This is apparently a well-known [cache problem with IE <10](https://stackoverflow.com/questions/5502002/jquery-ajax-producing-304-responses-when-it-shouldnt): Ajax responses are aggressively and often incorrectly cached.

There are at least two ways to solve this:

1. In the client, use `cache: false` in jQuery to append random junk to
    the request URL to make each URL unique.
2. On the server, add a `Cache-Control: no-cache` header to API endpoints
    to tell clients to never cache them. (IE honors this header).

Option 2. seems the best approach to me. The first is arguably easier to implement, but the server knows its API endpoints are frequently changing and should likely never be cached.

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

**Comment by aquamatthias** [comment]
Guess that will work most of the time.
There is a good explanation on that topic here: http://www.mobify.com/blog/beginners-guide-to-http-cache-headers/
According to that, we should take that parameters into account:

```
Cache-Control: no-cache, no-store, must-revalidate   // HTTP 1.1.
Pragma: no-cache  // HTTP 1.0.
Expires: 0 // Proxies.
```

**Comment by drexin** [comment]
@aquamatthias Added missing headers, please review.

**Comment by aquamatthias** [comment]
:ship: it.

**Comment by drexin** [comment]
Thank!

**Pull request merged**
