### PR TITLE
Fixes #2256 - Improve insufficient resources message

### LINKED ISSUE #2256: Misleading log message if offer doesn't match because of filtered roles
In the log below the offer contains the resources needed but with other roles. The logging should mention this. Maybe it should detect that some resources were filtered and add "only resources with role slave_public were considered." Or something similar.

```
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: [2015-09-15 10:08:47,469] INFO started processing 1 offers, launching at most 100 tasks per offer and 1000 tasks in total (mesosphere.marathon.task
s.IterativeOfferMatcher$:132)
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: [2015-09-15 10:08:47,469] INFO Offer [20150915-060341-302059692-5050-4851-O1638]. Not all basic resources satisfied: cpu not in offer, disk SATISFI
ED (0.0 <= 0.0), mem not in offer (mesosphere.mesos.ResourceMatcher$:121)
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: [2015-09-15 10:08:47,470] INFO Offer [20150915-060341-302059692-5050-4851-O1638]. Insufficient resources for [/oinker-router] (need cpus=1.0, mem=2
56.0, disk=0.0, ports=([80] required), available in offer:
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: id {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: value: "20150915-060341-302059692-5050-4851-O1638"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: framework_id {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: value: "20150915-060341-302059692-5050-4851-0000"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: slave_id {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: value: "20150915-060341-302059692-5050-4851-S2"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: hostname: "172.16.1.129"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: resources {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: name: "ports"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: type: RANGES
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: ranges {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 1025
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 2180
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 2182
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 3887
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 3889
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 5049
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 5052
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 8079
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 8082
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 8180
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 8182
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 9999
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 10001
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 25188
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: range {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: begin: 25191
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: end: 32000
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: role: "*"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: resources {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: name: "cpus"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: type: SCALAR
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: scalar {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: value: 38.99
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: role: "*"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: resources {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: name: "mem"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: type: SCALAR
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: scalar {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: value: 254658.0
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: role: "*"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: resources {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: name: "disk"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: type: SCALAR
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: scalar {
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: value: 741934.0
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: role: "*"
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: }
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: (mesosphere.mesos.TaskBuilder:72)
Sep 15 10:08:47 ma02.dcos.ca1.mesosphere.com java[4901]: [2015-09-15 10:08:47,470] INFO Offer [20150915-060341-302059692-5050-4851-O1638]. Decline with filter refuseSeconds=300.0(use --decline_offer_duration to reconfigure) (mesosphere.marathon.tasks.IterativeOfferMatcher$:223)
```

### PR DESCRIPTION
**Pull request by gkleiman**
- Log the list of roles that were considered.
- Log the offer using Protocol Buffer's shortDebugString() method. This
  includes the same information as toString(), but in a condensed form
  without line breaks.

### CODE REVIEW

**Comment by aquamatthias** [comment]
@gkleiman sounds good! Can you append an example log statement here?

**Comment by gkleiman** [comment]
Sure, I actually had it ready to paste it in the PR, but forgot to do so :flushed::

```
marathon [2015-10-21 17:29:45,430] INFO Offer ID: [20151021-172514-16777343-5050-36674-O3]. Considered resources with roles: [*]. Not all basic resources satisfied: cpu NOT SATISFIED (100.0 > 8.0), disk SATISFIED (0.0 <= 0.0), mem SATISFIED (16.0 <= 15360.0) (mesosphere.mesos.ResourceMatcher$:marathon-akka.actor.default-dispatcher-12)
marathon [2015-10-21 17:29:45,514] INFO Offer [20151021-172514-16777343-5050-36674-O3]. Insufficient resources for [/foobar] (need cpus=100.0, mem=16.0, disk=0.0, ports=(1 dynamic), available in offer:
marathon id { value: "20151021-172514-16777343-5050-36674-O3" } framework_id { value: "20151021-172514-16777343-5050-36674-0000" } slave_id { value: "20151021-172514-16777343-5050-36674-S0" } hostname: "localhost" resources { name: "cpus" type: SCALAR scalar { value: 8.0 } role: "*" } resources { name: "mem" type: SCALAR scalar { value: 15360.0 } role: "*" } resources { name: "disk" type: SCALAR scalar { value: 470816.0 } role: "*" } resources { name: "ports" type: RANGES ranges { range { begin: 31000 end: 32000 } } role: "*" } url { scheme: "http" address { hostname: "localhost" ip: "127.0.0.1" port: 5050 } path: "/slave(1)" } (mesosphere.mesos.TaskBuilder:marathon-akka.actor.default-dispatcher-12)
```

**Comment by aquamatthias** [comment]
General: We should improve the tools for offer matching problems, rather than polluting log files.
This PR improves the logging a lot - Thanks!

In order to merge:
- please remove the \n so it becomes one log line
- please wrap the whole expression in if (log.isInfoEnabled)

**Comment by gkleiman** [comment]
Comments addressed, PR updated.

**Comment by aquamatthias** [comment]
Thanks!

**Pull request merged**
