### PR TITLE
Don't store DeploymentPlan version nodes

### PR DESCRIPTION
**Pull request by gkleiman**

### CODE REVIEW

**Comment by aquamatthias** [comment]
Thanks! Please cherry pick in 1.2

**Comment by jdef** [comment]
should we have a "cherry-pick" label to track things like this?

**Comment by aquamatthias** [comment]
@jdef thanks for the suggestion. Added this label.
@gkleiman please remove this label when you are done.

**Comment by gkleiman** [comment]
This was already cherry-picked =)

**Pull request merged**
