### PR TITLE
Add checks to see if the current user is root before using sudo. Also…

### LINKED ISSUE #3007: haproxy-marathon-bridge script should not be run from install path when in install mode
The script should prevent user from attempting to run the script in install mode (install_haproxy_system) from the intended install path since doing so can cause the script file to be truncated or zero'd out.

e.g.

/usr/local/bin/haproxy-marathon-bridge install_haproxy_system localhost:8080

This will intermittently cause /usr/local/bin/haproxy-marathon-bridge to become empty.

### LINKED ISSUE #3008: haproxy-marathon-bridge script should not call sudo when executing as root
We should add check to haproxy-marathon-bridge to see if the current user is root before using sudo. On a container, sudo may not even be installed and the user will be root. It'd be nice if the script had the smarts to detect this scenario.

### PR DESCRIPTION
**Pull request by jlamillan**
Add checks to see if the current user is root before using sudo. Also, prevent user from attempting to run the script in install mode from the intended install path since doing so can cause the script file to be truncated. fixes #3007 fixes #3008

### CODE REVIEW

**Comment by aquamatthias** [comment]
@lloesche can you review please?

**Comment by lloesche** [comment]
@jlamillan thank you for the PR! I noticed the style doesn't match the existing one. For instance the existing code doesn't use backticks for command substitution.

But before updating let me check in with

@aquamatthias, didn't we code freeze the old haproxy-marathon-bridge as a minimum working example and point for more advanced use to https://github.com/mesosphere/marathon-lb
I remember rejecting several PRs because we didn't want to add any more complexity.

**Comment by aquamatthias** [comment]
@lloesche so your proposal is to delete this script from the repo?

**Comment by jlamillan** [comment]
I for one can attest that the script is a good working simple /
minimal example for people. I really hope it isn't deleted.

-Jesse

**Comment by lloesche** [comment]
No, we wanted to keep it as a minimum example of how to use the Marathon REST API. Imho it has value for that. But for production use marathon-lb is better suited. We should just add a deprecation/example disclaimer to the top of the bash script.

**Comment by aquamatthias** [comment]
Created a PR here #3023. The script is moved to the examples directory.

**Comment by aquamatthias** [comment]
Hey @jlamillan thanks for this PR 
The file has moved to the examples directory.
Can you please rebase your PR and address the comments from @lloesche?

**Comment by jlamillan** [comment]
Will do.

**Comment by jlamillan** [comment]
FYI - rebase is done. PR ready for re-review

**Comment by aquamatthias** [comment]
@jlamillan thanks! 
@lloesche can you review again please?

**Comment by lloesche** [comment]
lgtm

**Pull request merged**
