### PR TITLE
Adding frontend tests

### PR DESCRIPTION
**Pull request by mlunoe**

### CODE REVIEW

**Comment by mlunoe** [comment]
@ConnorDoyle Could you take a look at this? You don't have to look through the code (which is only tests, test-helper)Just

**Comment by mlunoe** [comment]
Thanks, didn't know how to do that :P

**Comment by mlunoe** [comment]
@drexin could you take a look too?

**Comment by ConnorDoyle** [comment]
:100:, LGTM

**Comment by ConnorDoyle** [comment]
We are seeing this consistently in the build logs:

```
> js2coffee@0.3.5 preinstall /home/travis/build/mesosphere/marathon/src/main/resources/assets/node_modules/broccoli-replace/node_modules/applause/node_modules/cson/node_modules/js2coffee
> node ./cyclic.js
-\/-|/\|-\/\|-\|-\/-npm WARN optional dep failed, continuing fsevents@0.3.4
```

Do we have a bad dependency listed?

**Comment by mlunoe** [comment]
No, it's an optional dependency from one of our dependencies. I read about it and it is no problem. Optional dependencies are.. well... optional

**Comment by mlunoe** [comment]
From google groups https://groups.google.com/forum/#!topic/nodejs/Drz2hvmnryU:
> "FSEvents is an API only available on OS X"

**Pull request merged**
