### PR TITLE
Resolves #3505 by adding documentation for ReadinessChecks

### LINKED ISSUE #3505: Scheduler Migrations: AppDefinition documentation
Documentation for #3500.

Context: We want to be able to drive scheduler upgrades manually. See [MARATHON-856](https://mesosphere.atlassian.net/browse/MARATHON-856) (private, sorry).

### PR DESCRIPTION
**Pull request by meichstedt**

### CODE REVIEW

**Comment by meichstedt** [comment]
Hi @sascala I've put together basic doc for Readiness Checks. Can you please have a look?

**Comment by meichstedt** [comment]
@sascala I've added a minor fix, please update your local branch via
```
git checkout me/3505-readiness-checks-docs
git pull origin me/3505-readiness-checks-docs
```

**Comment by sascala** [comment]
From a text perspective, I think this doc is a fine start (I'd want to add some examples/more information in the future). Can I test it out?

**Comment by aquamatthias** [comment]
Can we merge this?

**Comment by meichstedt** [comment]
@aquamatthias yes please.

**Comment by meichstedt** [comment]
@sascala you can test it, but you won't really _see_ anything.

**Pull request merged**
