### PR TITLE
Remove FraemworkId from Scheduler Service

### PR DESCRIPTION
**Pull request by janisz**
Use FrameworkIdRepository directly instead of wrapping it
with MarathonSchedulerService.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4763" target="_blank">ReviewNinja

**Comment by jasongilanfarr** [comment]
Ok to test

**Comment by jasongilanfarr** [comment]
@janisz Thanks for taking on this TODO

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by aquamatthias** [comment]
@janisz Thanks

**Pull request merged**
