### PR TITLE
take app instances into account when detecting volume conflicts

### PR DESCRIPTION
**Pull request by jdef**
xref https://github.com/mesosphere/marathon/pull/3737/files#r59401585
xref #3723

### CODE REVIEW

**Comment by jdef** [comment]
xref #3563

**Comment by sttts** [comment]
If you scale up the suspended app again, tasks will fail. Or do we get a proper error message then from the scaling API endpoint?

**Comment by kolloch** [comment]
What is the use case of this? You have multiple app definitions that access the same volume and sometimes you suspend A and start B, sometimes you suspend B and start A?

I would not allow this for simplicity. You can still destroy A and create B or the other way around.

There are also race-conditions involving this that are more likely to occur if you encourage this kind of pattern. Removing an app does not remove all tasks instantaneously, therefore temporarily there could exist tasks accessing the same volume.

**Comment by jdef** [comment]
@kolloch I don't think I had a specific use case in mind, it just seemed intuitive that I'd be able to define multiple apps that reference the same vol as long as the number of task instances that reference the same volume is limited to 1.

Yes, I can see how this could be a bit racy. In a race we'd depend on the underlying provider to generate an error on task-launch if multiple running tasks referenced the same volume instance. Since tasks are respawned indefinitely in Marathon the system should eventually settle into a stable state since the "desired end state" only allows 1 task instance per volume.

@sttts no, the error messages sent back from the isolator are not very informative; as we say in the docs users are basically expected to grep the agent/system logs to troubleshoot.

**Comment by sttts** [comment]
@jdef I meant the error message from the Marathon REST API when scaling a 0-instance app to 1 instance.

**Comment by aquamatthias** [comment]
I would also recommend to make sure to check the App<-> Volume relationship, even if there are currently no running tasks. 
Close this for now, if we don't see any specific use case for this.

**Pull request closed without merging**
