### PR TITLE
Add Network.Name to IpAddress

### PR DESCRIPTION
**Pull request by djosborne**
This PR adds the optional field `ipAddress.Name`, which is read and written as an optional field in `ContainerInfo.NetworkInfo.Name`.

This branch successfully builds but fails to pass the existing tests, presumably because I am incorrectly reading and storing the nullable string from the protobuf. 

Not looking to merge this until the first commit (bump to Mesos 1.0.0 protobufs) is mainlined through the official mesos-utils build system. But am looking to get this working ASAP as early access to CNI plugins. Can anyone provide some scala-foo for what I may be doing wrong?

### CODE REVIEW

**Comment by djosborne** [comment]
Some sample test failures:
```
- BuildIfMatchesWithIpAddress *** FAILED *** (6 milliseconds)
  0 was not equal to 1 (TaskBuilderTest.scala:588)
```

```
- BuildIfMatchesWithIpAddressAndCustomExecutor *** FAILED *** (6 milliseconds)
  0 was not equal to 1 (TaskBuilderTest.scala:639)
```

```
- BuildIfMatchesWithIpAddressAndDiscoveryInfo *** FAILED *** (4 milliseconds)
  0 was not equal to 1 (TaskBuilderTest.scala:694)
```

```
- ConstructFromProto with default proto *** FAILED *** (1 millisecond)
  IpAddress(Vector(),Map(),DiscoveryInfo(List()),Some()) did not equal IpAddress(List(),Map(),Discove
ryInfo(List()),None) (IpAddressTest.scala:97)
```

**Comment by djosborne** [comment]
Cool, I was just missing one embarrassing line. This all seems to be working now. Is there any other work that needs to be done while we wait for 1.0.0 mesos-utils to drop? Presumably just:
- tests
- documentation

**Comment by jdef** [comment]
just merged this morning: https://github.com/mesosphere/marathon/commit/731b4d4ee7de2e48417c7b4a7833a6050e0b898a

if this meets the need, can we close this out?

**Comment by kensipe** [comment]
@djosborne is the feature merge provided by jdef sufficient?  can we close this?

**Comment by djosborne** [comment]
@kensipe I built from master last week after it was merged and was unable to get a task to launch with CNI. I will retry with latest master and close if it works, or post debug info if it does not.

**Comment by djosborne** [comment]
Just got this working. The network names that have been added are sufficient for CNI for Mesos tasks. 

FYI I was running into an issue where Marathon was complaining that 1.0.0 was compatible because of 0.28.0. Looks like the main `Dockerfile` installs Mesos 0.28.2, whereas `Dockerfile.development` correctly installs 1.0.0-rc1. I can raise an issue if this is not being tracked

**Comment by djosborne** [comment]
@jdef Just launched a Docker task on a Docker UDN using the new Api. All worked as expected. Nice!

**Comment by jkidambi** [comment]
Is there a plan to support the labels field mentioned in http://mesos.apache.org/documentation/cni/?

**Comment by djosborne** [comment]
@jkidambi That's currently supported. Marathon's `ipAddress.labels` field gets pushed into `Networkinfo.labels`. More info here: https://mesosphere.github.io/marathon/docs/ip-per-task.html

**Comment by jkidambi** [comment]
@djosborne Thanks. I did figure that out after I posted that question, and have been able to successfully test it end-to-end.

**Comment by jkidambi** [comment]
@djosborne Is there a way to specify multiple networks per container? I'm not seeing a way to do that. If there is a better place to post such questions, I'll do so.

**Comment by djosborne** [comment]
@jkidambi I don't think there is currently. I think since configurable networking for Mesos is a relatively new concept, use cases for multi-network tasks hasn't been clearly ironed out yet, and there's not a lot of support for it yet.

(Also note that though there's a "Mesosphere member" label next to my name, I am not employed by Mesosphere, and don't maintain any of their software - I work on Project Calico)

**Pull request closed without merging**
