### PR TITLE
Fix for event stream tests with multimaster

### PR DESCRIPTION
**Pull request by alenkacz**
Summary:
Event stream tests were failing after switch to multimaster. The reason for that is that all the commands were talking to (mesos) master but there are multiple masters now so the commands might be executed on different nodes. Now I do the curl always on marathon leader to make that deterministic.

JIRA issues: MARATHON-7943

### CODE REVIEW

**Comment by kensipe** [comment]
doesn't pass flake8

```
tests/system/fixtures/__init__.py:43:13: E128 continuation line under-indented for visual indent
tests/system/fixtures/__init__.py:44:13: E128 continuation line under-indented for visual indent
tests/system/fixtures/__init__.py:45:13: E128 continuation line under-indented for visual indent
tests/system/fixtures/__init__.py:50:13: E128 continuation line under-indented for visual indent
tests/system/fixtures/__init__.py:51:13: E128 continuation line under-indented for visual indent
```

**Comment by kensipe** [comment]
@alenkacz fixed the python syntax issues and rebased

**Comment by zen-dog** [comment]
> I'm ok with this... but I would MUCH rather have a run_command_on_leader function in shakedown.
we could move this method into our `common.py * Methods to move to shakedown in the future*` and migrate them eventually. However I'm more concerned about making marathon SI tests green now.

**Comment by kensipe** [comment]
https://github.com/dcos/shakedown/pull/178

**Comment by zen-dog** [comment]
> Is it hard to extend shakedown? Or why not do it right ahead?

you'll need to extend shakedown (PR) and release a new version. Both can take some time. It's usually faster to fix it in `common.py` and move a bunch of methods to shakedown eventually.

**Pull request merged**
