### PR TITLE
Actually embedding tasks again

### PR DESCRIPTION
**Pull request by bobrik**
#1105 fixed it, but looks like conflicts in #914 broke it again. Here's the fix.

I hope somebody would add tests for this eventually :)

### CODE REVIEW

**Comment by bobrik** [comment]
cc @sttts

**Comment by drexin** [comment]
Oh, good catch. Thanks! I will merge this after the test run.

**Comment by drexin** [comment]
:+1:

**Comment by sttts** [comment]
:+1:

**Pull request merged**
