### PR TITLE
Remove deprecated configuratio option

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4755" target="_blank">ReviewNinja

**Comment by aquamatthias** [comment]
@janisz It is probably a good time to get rid of some deprecations. 
- Since this property is also described in command-line-flags.md, can you remove it there as well?
- Short line in the changelog would be awesome

**Comment by aquamatthias** [comment]
ok to test

**Comment by janisz** [comment]
@aquamatthias My bad, I've only check code. Added changelog entry and removed all entries of `marathon_store_timeout`

**Pull request merged**
