### PR TITLE
Added leaderDuration metric

### PR DESCRIPTION
**Pull request by prsekar**
Addressing the issue,
https://github.com/mesosphere/marathon/issues/3010

Created a metric service.mesosphere.marathon.leaderDuration that gets reset every time a node is elected as a leader, removed everytime its defeated

### CODE REVIEW

**Comment by prsekar** [comment]
@kolloch Could you review this and let me know if its good enough. Thanks

**Comment by jolexa** [comment]
:+1: 

Can docs be updated as well? https://mesosphere.github.io/marathon/docs/metrics.html

**Comment by prsekar** [comment]
@jolexa Added the docs as well. Thanks

**Comment by prsekar** [comment]
@jolexa  @kolloch Is this good for a merge ?

**Comment by jolexa** [comment]
I'm just a community member, not a contributor. I do think this is a useful metric though :)

**Comment by kolloch** [comment]
Thanks, this looks great! :100: 

Sorry for the delay. Very busy currently.

**Pull request merged**
