### PR TITLE
MARATHON-100: Making url paths relative to enable proxied pathnames

### PR DESCRIPTION
**Pull request by aldipower**
This enables the Marathon UI to act through a proxied request, by making paths relative, f.ex.:
http://cluster/marathon/#apps

### CODE REVIEW

**Comment by mlunoe** [comment]
Why not use "./" relative paths? Either way, this looks good to me

**Comment by aldipower** [comment]
Hey!
Because this adds additional 16 bit in ASCII to the pathname. We could save that memory by do not so. Take care of the bits and the bytes will take care of themselves. ;)
Otherwise can you explain the advantage of adding this or is it a favour?
Thanx for looking over it!

**Comment by mlunoe** [comment]
For me it is only to make it explicit. There is no real difference. I don't care about those extra characters, I care about it being explicit and understandable. Again, this is my preference and I understand if you will keep your way.

**Comment by philipnrmn** [comment]
I don't have an opinion either way, but given that this is a priority ticket I'm going to hit the merge button now. Might I suggest that you start a PR with `./` paths so we can have the discussion without time pressure?

Hope this approach isn't too bombastic :)

**Comment by mlunoe** [comment]
:+1:

**Pull request merged**
