### PR TITLE
Added regression test for leadership abdication.

### PR DESCRIPTION
**Pull request by jparkie**
Added regression test for leadership abdication as reproduced in https://github.com/EvanKrall/reproduce_marathon_issue_3783 for https://github.com/mesosphere/marathon/issues/3783.

### CODE REVIEW

**Comment by jasongilanfarr** [comment]
Ok to test

**Comment by jasongilanfarr** [comment]
Ok to test

**Comment by jparkie** [comment]
What does it mean when none of the integration tests failed, but the overall Jenkins task is a failure: https://jenkins.mesosphere.com/service/jenkins/job/public-marathon-unit-integration-tests-pulls/1819/

I see my test did not fail though: https://jenkins.mesosphere.com/service/jenkins/job/public-marathon-unit-integration-tests-pulls/1819/testReport/mesosphere.marathon.integration/LeadershipAbdicationRegressionTest/

**Comment by jasongilanfarr** [comment]
In your case, a test crashed so it wasn't reported as a failure. I'm adding logic to Terminate the leader on abdication/lose of leadership, will this logical change break this test?

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jparkie** [comment]
If the leader terminates and the tasks that are deploying get lost or killed, I think that would be a problem. I believe the pain point in the issue is that upon several leadership abdications, tasks which were deploying/deployed get killed.

**Comment by jparkie** [comment]
@jasongilanfarr Hi! Can I have status update?

**Comment by jasongilanfarr** [comment]
I have some test failures to work through (they weren't exactly designed for marathon to just die and I can't easily prevent it from not doing that in a test). Im debating turning them off until another set of changes come in regarding integration tests. I hoped to get to this all today but was working out another ZK connectivity blocker where we were supposed to exit but weren't actually exiting.

I'm thinking we should likely spin 1.3.6 with both changes incorporated and I'm hoping to polish the linked review tomorrow.

Given that we're going to just kill marathon on abdication, do you think this will fix your issue, assuming a watchdog is restarting it? If not, I'll prioritize a thorough review of this PR tomorrow.

Appreciate the effort by the way, just want to make sure my change doesn't make yours totally obsolete almost immediately. I wish I was checking the github issues to let you know I was tackling a related issue on the same day.

**Comment by jparkie** [comment]
```
Given that we're going to just kill marathon on abdication, do you think this will fix your issue, assuming a watchdog is restarting it?
```

I think it will.

**Comment by jdef** [comment]
we recently landed updates to marathon (master) re: termination upon leader abdication. PTAL

https://phabricator.mesosphere.com/D302

**Comment by unterstein** [comment]
Hi @jparkie,

Your Commit was taken over and adapted within this PR, together with the fix: https://github.com/mesosphere/marathon/pull/4900

Thanks for reporting and writing the integration test 🎉

**Pull request closed without merging**
