### PR TITLE
Documented task environment variables.

### PR DESCRIPTION
**Pull request by ConnorDoyle**

### CODE REVIEW

**Comment by kolloch** [comment]
That's a great patch. What can I do to make it coming along? @ConnorDoyle 

I could extend it myself if you are to busy.

**Comment by ConnorDoyle** [comment]
@kolloch feel free to take this over if you have spare cycles

**Comment by drexin** [comment]
:+1:

**Comment by bobrik** [comment]
@ConnorDoyle there are more cases for `PORT` env variable. For the next mapping:

```yaml
            portMappings:
              - containerPort: 80
                servicePort: 14000
```

+

```yaml
        ports:
          - 14000
```

Env variables from docker container:

```json
        [
            "PORT=31000",
            "PORTS=31000",
            "PORT_80=31000",
            "PORT0=31000",
        ]
```

`PORT_80` is not documented.

For container with host networking:

```yaml
        ports:
          - 12001
```

interesting env variables are:

```json
        [
            "PORT_12001=31622",
            "PORT=31622",
            "PORTS=31622",
            "PORT0=31622",
        ]
```

`PORT_12001` is not documented here.

**Comment by kolloch** [comment]
Actually, I made a conscious decision not documenting them because I am not really sure about their use case. Their pattern is `PORT_<service port>` and they contain the corresponding instance/container port number.

But you are right, it could be confusing to see additional environment variables without documentation.

What do you think, @bobrik ?

**Comment by bobrik** [comment]
They exist, therefore they should be documented. I bet you could ask people in the office about those variables if you're not sure :)

**Pull request merged**
