### PR TITLE
remove redundant use of '-Ywarn-unused-import' scalac option

### PR DESCRIPTION
**Pull request by natemurthy**
The `-Ywarn-unused-import` flag is set twice in `build.sbt`. The `scalacOptions in Compile` for `commonSettings` needs only to set this flag once.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4798" target="_blank">ReviewNinja

**Comment by jasongilanfarr** [comment]
ok to test

**Comment by natemurthy** [comment]
@jasongilanfarr @janisz Would either of you happen to know why the Velocity Integration Tests and Package keep failing. I don't have OneLogic creds. But I'm seeing this on the public Jenkins server:

https://jenkins.mesosphere.com/service/jenkins/job/public-marathon-unit-integration-tests-pulls/1943/console

**Comment by jasongilanfarr** [comment]
retest this please

**Comment by jasongilanfarr** [comment]
Hi @natemurthy I believe this is now fixed.

**Comment by natemurthy** [comment]
@jasongilanfarr So now "Velocity - Integration Tests" pass but "Velocity - Mesos Integration Tests" do not.

**Pull request merged**
