### PR TITLE
Log events and deployment id in integration tests.

### PR DESCRIPTION
**Pull request by jeschkies**
Get a little more insight into errors such as `java.lang.AssertionError: Waiting for event status_update_event to arrive took longer than 30 seconds. Give up.`.

This closes #4339.

### CODE REVIEW

**Comment by jeschkies** [comment]
retest this please

**Comment by aquamatthias** [comment]
:ship: it

**Comment by unterstein** [comment]
jsstring

**Comment by unterstein** [comment]
retest this please

**Pull request merged**
