### PR TITLE
New build system

### PR DESCRIPTION
**Pull request by mlunoe**
Introducing new workflow for frontend using npm, broccoli and webpack. Also adding jshint- and jscs-checking, which fails right now. Will create a PR with the style changes to conform with these style guides.

### CODE REVIEW

**Comment by mlunoe** [comment]
@samccone Would you be interested in reviewing?

**Comment by mlunoe** [comment]
@pyronicide maybe also you could have a look?

**Comment by samccone** [comment]
Hey @mlunoe do you think you can go through and do some squashing to convert these into "atomic" commits 

there seems to be a few commits all related to the new build system that could most likely be a single commit.

There is also the jshint update and all the code changes needed that could be all one commit I think... what do you think?

**Comment by mlunoe** [comment]
This should look a little more comprehensible, hopefully. Care to take a look @samccone?

**Comment by samccone** [comment]
:clap: will do

**Comment by mlunoe** [comment]
Thank you

**Comment by samccone** [comment]
Overall this is really good @mlunoe , some minor cleanup but really impressive work. I think this will make working on the front end __much__ easier

:clap: :clap: :clap: :clap:

**Comment by aldipower** [comment]
This is really really cool. Great work!
Broccoli is such a powerful tool and a big advantage over other js build tools.
Especially the new require notation is cool. Feels like in Node.js now. ;)
Also the .jscs-file is a good thing to harmonize our code style, so we could remove jshint?

**Comment by mlunoe** [comment]
Thanks :) jshint takes care of some other stuff that jscs cannot, so let's keep them both :)

**Comment by mlunoe** [comment]
Ok, if there are no other change requests to this I will merge in 24h. @ConnorDoyle @drexin Feel free to give my your final comments.

**Comment by samccone** [comment]
very nice all of the comments should go away once you force push over your branch

**Comment by drexin** [comment]
:100: This is great! Thanks a lot for your efforts!

**Comment by samccone** [comment]
:clap: :clap: :clap:  :tada: excited for this

**Pull request merged**
