### PR TITLE
Fix docs for --checkpoint and --failover_timeout.

### LINKED ISSUE #1089: Docs say checkpoint is default false
http://mesosphere.github.io/marathon/docs/command-line-flags.html#optional-flags

### PR DESCRIPTION
**Pull request by ConnorDoyle**
- Fixes #1089.

### CODE REVIEW

**Comment by bobrik** [comment]
Are you sure that failover requires checkpointing? I can't find that in mesos docs.

**Comment by ConnorDoyle** [comment]
Yep.

**Comment by ConnorDoyle** [comment]
That is, assuming you want your tasks to survive the failover (and I can't think of another reason to increase the failover timeout).

**Comment by drexin** [comment]
:+1:

**Pull request merged**
