### PR TITLE
Fixes #3899 by waiting for readiness and health before a task is replaced

### LINKED ISSUE #3899: Upgrade doesn't wait for readiness check
Currently an app upgrade doesn't wait for readiness checks to pass. As soon as the app is healthy the old version is taken down, even though the readiness checks haven't succeeded yet.

### PR DESCRIPTION
**Pull request by aquamatthias**

### CODE REVIEW

**Comment by meichstedt** [comment]
LGTM!

**Comment by meichstedt** [comment]
@aquamatthias `ReadinessCheckIntegrationTest` seems to fail

**Comment by aquamatthias** [comment]
Needs to be cherry picked in 1.3

**Comment by unterstein** [comment]
retest this please

**Comment by meichstedt** [comment]
Thanks!

**Comment by meichstedt** [comment]
cherry picked in 1.3

**Pull request merged**
