### PR TITLE
Fixed broken integration with scheduler plugin

### PR DESCRIPTION
**Pull request by tsydd**
Integration with SchedulerPlugin is broken. I've made `shedulerPlugins` parameter obligatory and fixed tests

### CODE REVIEW

**Comment by jeschkies** [comment]
@tsydd, thanks for you efforts.

> Integration with SchedulerPlugin is broken. I've made shedulerPlugins parameter obligatory and fixed tests

Which integration tests do you mean? If we don't run them in our pipeline we have to change that.

**Comment by alenkacz** [comment]
@jeschkies I think he meant tests in general, not integration tests... and those are fixed as part of this PR. There is probably no integration test at all ... ? (or is there? @kensipe )

**Comment by zen-dog** [comment]
> Which integration tests do you mean? 
Some tests has now one parameter more (e.g. `schedulerPlugins: Set[SchedulerPlugin] = Seq.empty`). However we don't currently test plugin integration at all in marathon ITs.

**Comment by jeschkies** [comment]
@alenkacz our CI should catch these issues. So we don't run everything?

**Comment by jeschkies** [comment]
Ok, I've misread the comment. Apparently we do not have tests. How could we have prevented this from breaking in the first place?

**Pull request merged**
