### PR TITLE
Move new application introduction into its own guide.

### PR DESCRIPTION
**Pull request by ssk2**

### CODE REVIEW

**Comment by ssk2** [comment]
cc @mhausenblas, @air, @joel-hamill

**Comment by mhausenblas** [comment]
LGTM, thanks for this @ssk2 — once it is stable I'l extend `docs/application-basics.md` with more examples/screen shots.

**Comment by air** [comment]
LGTM

**Comment by ssk2** [comment]
@mhausenblas - merged, please feel free to extend :)

**Comment by mhausenblas** [comment]
Challenge accepted @ssk2—ETA: this W/E :)

**Pull request merged**
