### PR TITLE
Parse JSON event only once before broadcast

### PR DESCRIPTION
**Pull request by janisz**
Current implementation parses events for every callback.
This patch make parsing happen only once for event.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4771" target="_blank">ReviewNinja

**Comment by jdef** [comment]
ok to test

**Comment by jasongilanfarr** [comment]
Can you rebase so we can merge?

**Comment by janisz** [comment]
Done

**Pull request merged**
