### PR TITLE
Task documentation reformatting (automatic)

### PR DESCRIPTION
**Pull request by kolloch**
I didn't run the automatic formatting when submitting this documentation change.

### CODE REVIEW

**Comment by gkleiman** [comment]
@kolloch are you sure we want to merge this? It breaks the beautiful ascii art!

**Comment by kolloch** [comment]
you are right! What have I done! (nearly)

**Comment by gkleiman** [comment]
```

           ~                  ~
     *                   *                *       *
                  *               *
  ~       *                *         ~    *          
              *       ~        *              *   ~
                  )         (         )              *
    *    ~     ) (_)   (   (_)   )   (_) (  *
           *  (_) # ) (_) ) # ( (_) ( # (_)       *
              _#.-#(_)-#-(_)#(_)-#-(_)#-.#_    
  *         .' #  # #  #  # # #  #  # #  # `.   ~     *
           :   #    #  #  #   #  #  #    #   :   
    ~      :.       #     #   #     #       .:      *
        *  | `-.__                     __.-' | *
           |      `````"""""""""""`````      |         *
     *     |         | ||\ |~)|~)\ /         |    
           |         |~||~\|~ |~  |          |       ~
   ~   *   |                                 | * 
           |      |~)||~)~|~| ||~\|\ \ /     |         *
   *    _.-|      |~)||~\ | |~|| /|~\ |      |-._  
      .'   '.      ~            ~           .'   `.  *
  jgs :      `-.__                     __.-'      :
       `.         `````"""""""""""`````         .'
         `-.._                             _..-'
              `````""""-----------""""`````
```

**Comment by kolloch** [comment]
😄

**Pull request merged**
