### PR TITLE
WIP: Security flaw in build script.

### PR DESCRIPTION
**Pull request by jeschkies**
If I'm not mistaken anybody can trigger a build and just echo our docker hub password.

### CODE REVIEW

**Comment by jeschkies** [comment]
As I thought it works.

**Comment by jasongilanfarr** [comment]
:( we need to get into build-pipeline to actually fix this.

**Comment by kensipe** [comment]
this is only true if the push to docker is built on a public jenkins.  we publish from a private build.

**Comment by jeschkies** [comment]
I could access the logs when I was not logged in.

**Pull request closed without merging**
