### PR TITLE
Remove unused functionality from WhenLeaderActor

### PR DESCRIPTION
**Pull request by kolloch**

### CODE REVIEW

**Comment by kolloch** [comment]
Yet another rebase...

**Comment by aquamatthias** [comment]
LGTM. Why don't we need this functionality any longer? Even if we don't need it now, could it make sense to have it in the future?

**Comment by kolloch** [comment]
@aquamatthias I can't predict the future. I am not sure what's best. If actors use this functionality, they are coupled to the WhenLeaderActor logic and they save only a few lines of code.

**Comment by aquamatthias** [comment]
LGTM. Thanks!

**Pull request merged**
