### PR TITLE
Make app version component nicer

### PR DESCRIPTION
**Pull request by bobrik**
- Units now live with values, Memory (MB): 8 -> Memory: 8 MB
- Container json is now pretty-printed

Before:

before

After:

after

"Before" is taken from 0.8.1 because there's no 0.8.2-RC1 on docker hub :(

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
@bobrik -- just triggered a [Docker build](https://registry.hub.docker.com/u/mesosphere/marathon/build_id/18663/code/bixdw2cqsubz2qyqn7anbad/) for the new tag, should be available soon.

**Comment by bobrik** [comment]
@ConnorDoyle :+1: , that should be included in regular release process though.

**Comment by bobrik** [comment]
Looks like most of the builds failed for some reason.

**Comment by ConnorDoyle** [comment]
Agreed, I think it was just overlooked this time around.  We have Marathon set up as a dockerhub ABR (Automated Build Repository) which is somewhat of a misnomer because it doesn't pick up new git tags automatically.  For some other projects we have our CI server push 1:1 docker tags for git tags so perhaps we'll look into switching how this is done.  Meanwhile I'll take a look at why they may have failed.

**Comment by bobrik** [comment]
Okay, I just sent an email to docker to ask for automated pick up of new tags and build error reporting. Let's see if that can be done from their side, since I'd love to have that feature for my projects as well.

If you switch to building artifacts from CI, make sure to use check out my [Dockerfile](https://github.com/mesosphere/marathon/pull/1427#issuecomment-96012829), it's much better if you have compiled jar already.

Thanks!

**Comment by kolloch** [comment]
LGTM

**Comment by bobrik** [comment]
Thanks! :tada:

**Pull request merged**
