### PR TITLE
Remove race condition where deployments start before an app is current

### PR DESCRIPTION
**Pull request by sttts**
The deployment step actor starts before the AppRepository has marked the app definition as the current definition. When the step actor now adds the new app to the taskQueue and and offer arrives right away, the MarathonScheduler will purge the not-current new app version from the taskQueue.

This patch turns the order around of marking the app as current and starting the deployment step actors.

### CODE REVIEW

**Comment by jaytaylor** [comment]
@sttts Do you think this scenario is a good candidate to have unit-tests for?

**Comment by sttts** [comment]
@jaytaylor not really. It's not observable from outside of the DeploymentActor when the deployment step actors are started right now. Moreover, we probably need some tricky trap construction to catch this race, not worth the work IMO.

Instead I have made it much more explicit now which deployment steps should wait for the AppDefinition store call.

**Comment by jaytaylor** [comment]
I see.  Thank you for following up and explaining your reasoning!

**Comment by drexin** [comment]
:100:

**Pull request merged**
