### PR TITLE
Add option to force docker pull

### PR DESCRIPTION
**Pull request by ConnorDoyle**
Fixes ##837.

TODO:

- [x] Release a `0.22.0` version of mesos-utils.
- [x] Update the mesos-utils dependency version in the Marathon build definition.
- [x] Update documentation to describe the new parameter.

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Blocked by #1340

**Comment by ConnorDoyle** [comment]
Needs a rebase.

**Comment by ConnorDoyle** [comment]
Rebased.

**Comment by ConnorDoyle** [comment]
@drexin Ready for review.

**Comment by mindscratch** [comment]
this is related to #681 as well.

**Comment by drexin** [comment]
@ConnorDoyle Could you please rebase again and squash it into a single commit?

**Comment by dontrebootme** [comment]
Ran into this today and glad to find this is already in progress. Thanks for efforts to everyone involved.

**Comment by ConnorDoyle** [comment]
@drexin: rebased

**Comment by drexin** [comment]
:100:

**Comment by ConnorDoyle** [comment]
@hekaldama yes, it will be in the next version (`0.8.2`) for which we will tag the first release candidate very soon now.

**Pull request merged**
