### PR TITLE
front end cleanup

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by samccone** [comment]
After opening this PR I see the work done in #976 
This PR ideally can be added as a small iterative piece on the road to the goal of #976 seems like @mlunoe and I have about the same goals in mind :) 

I just took a bit smaller bite out of the :apple:

**Comment by mlunoe** [comment]
Since we added the new building system I'm going to close this one.

**Comment by samccone** [comment]
no prob

**Comment by samccone** [comment]
I think we can prob cherry pick a few of these but I will open a new PR

**Pull request closed without merging**
