### PR TITLE
WIP: 2419 - implement leader election with Apache Curator

### PR DESCRIPTION
**Pull request by sttts**
Fixing https://github.com/mesosphere/marathon/issues/1310.

### CODE REVIEW

**Comment by sttts** [comment]
@aquamatthias @gkleiman ptal

This implements the twitter common Candidate interface using the curator leader election, i.e. it's a drop-in for the old algorithm. Further refactoring of the whole leader election code makes probably sense, but that's not (yet) part of this PR.

Of course, the old and the new leader election are not compatible. Do you think it's worth to invest in a more graceful switch? At least, we could implement something along these lines:

- check whether leader-v2 Zookeeper key exists
  (a)
    - if not, switch to **old** leader election
    - listen for leader-v2 key creation. If created, switch to **new** leader election
  (b) if yes, use **new** leader election directly
- if a **new** marathon becomes leader (using the old leader election)
  - check whether there are **old** marathons in the Zookeeper group (we could mark the new ones with a special postifix in the supplier key)
  - if not, create leader-v2 key and switch to the new election code

**Comment by aquamatthias** [comment]
@sttts 

1) Regarding backward compatibility: very good point.Learning from the past, leader election has been a big problem and can lead to even bigger problems if done correctly. To complicate things, we also have something like an AbdicateOnConnectionLossActor, which probably only makes sense in combination with twitters library (because it does not handle that case).
Pros of this approach:
- migration to a newer version is supported
Cons:
- we have to maintain 2 versions
- added complexity, because we have to check with every leader election, which protocol to use
- it will only solve the forward problem (a rollback to an older Marathon version would not work)
My gut feeling is: if we can make the leader election implementation a drop in replacement (curator/twitter), it is probably worth the effort. What do you think?

2) I really would encourage to refactor the structure we have. 

3) Can you make some tests, if the new leader election library is resistant against zk connection problems or timeouts. This is the main reason why we do this.

**Comment by sttts** [comment]
@aquamatthias as far as I see `AbdicateOnConnectionLossActor` does not harm. I would leave it in as long as we maintain compatibility with the old leader election.

**Comment by sttts** [comment]
Superseeded by #3777

**Pull request closed without merging**
