### PR TITLE
Use EntityCacheStore for EventSubscribers

### PR DESCRIPTION
**Pull request by aquamatthias**
Cherry pick for 0.13

### CODE REVIEW

**Comment by kolloch** [comment]
Can we somehow learn from this mistake and prevent something like that happening again in the future?

Otherwise: LGTM!

**Comment by aquamatthias** [comment]
Guess the main reason for that was the fact, that all repos were created in one place, but not this one. Do you have a suggestion?

**Comment by kolloch** [comment]
cherry picked to releases/0.13

**Comment by kolloch** [comment]
probably you are right. That's sufficient.

I was thinking along the lines of checking whether there is an entityStore bound by guice that's not cached, making the uncached EntityStore package private, stuff like that.

**Pull request merged**
