### PR TITLE
Remove misleading logging on GET /v2/info

### PR DESCRIPTION
**Pull request by gkleiman**

### CODE REVIEW

**Comment by kolloch** [comment]
Looks good!

**Comment by kolloch** [comment]
Maybe also remove the FIXME?

**Comment by gkleiman** [comment]
The FIXME is still true. That method is only called by `InfoResource`, so it might be better to pass a `FrameworkIdUtil` instance to it and remove the method and `frameworkIdUtil` from `MarathonSchedulerService`.

**Comment by kolloch** [comment]
:rocket:

**Pull request merged**
