### PR TITLE
Log akka configuration on start

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4667" target="_blank">ReviewNinja

**Comment by jasongilanfarr** [comment]
ok to test

**Comment by jasongilanfarr** [comment]
I like this overall. I'm a bit concerned that it could expose secrets since the command line and environment variables are in the full config. Any thoughts @janisz

**Comment by janisz** [comment]
You're right it's not necessary and potentially dangerous. I saw config is printed in metronome and thought that could be useful for tuning akka configuration.

**Comment by jasongilanfarr** [comment]
I think the right way to do this would be to load the config ourselves
(passing it to the actor system) and log it out with secret like things
masked out.

**Pull request closed without merging**
