### PR TITLE
Remove unused InstanceTracker method

### PR DESCRIPTION
**Pull request by janisz**
Releates to: #3031

### CODE REVIEW

**Comment by janisz** [comment]
Rebased

**Comment by aquamatthias** [comment]
test this please

**Comment by aquamatthias** [comment]
@janisz sorry we were not fast enough. Can you resolve the conflict?

**Comment by janisz** [comment]
No problem. I'll do it next week.

**Comment by janisz** [comment]
@aquamatthias Rebased

**Comment by aquamatthias** [comment]
ok to test

**Comment by aquamatthias** [comment]
Thanks!

**Pull request merged**
