### PR TITLE
Simplify InstanceTracker by removing unused method

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4795" target="_blank">ReviewNinja

**Comment by jasongilanfarr** [comment]
ok to test

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
Sorry for editing two times. Will merge after tests passed :)

**Comment by jasongilanfarr** [comment]
retest this please

**Pull request merged**
