### PR TITLE
Update version after scaling

### PR DESCRIPTION
**Pull request by sttts**
When an app is scaled with existing tasks, the version of the new and of the old
tasks was different. This looked confusing in the UI for the user.

This patch updates all the old tasks at the end of the scaling deployment step.

Backend part of the fix for #1025

### CODE REVIEW

**Comment by sttts** [comment]
For @drexin and @ConnorDoyle: is there a better way to update many tasks at once than calling `store` n times?

**Comment by ConnorDoyle** [comment]
I'm not convinced that rewriting the version history is the right thing to do.  What problem does this solve?

**Comment by sttts** [comment]
I am not convinced 100%  either, but IMO we have some kind of inconsistency in our concepts about apps:

- there is an app `definition`, 
- there is the app `version` and
- there is the app `instances` value.

In my world view, `version` is a revision of the target cluster state regarding the app, where transitions are modeled with deployments. Therefore the `version` shall be strictly increasing with every deployment.

For the app `definition` we have basically two options:
- it describes the target state of the cluster regarding an app, i.e. all its instances
- it describes only how a task looks like and how it is handled within its life-cycle (health, upgradeStrategy, etc.).

Right now we have a mix: the app `definition` does the second and the last ("current") app `definition` does the first. This is strange.

This patch tries to implement the first by updating the AppDefinition for old tasks.

From my experience using the Marathon API in a continuous deployment setup, it would make more sense to separate app state and app definition, i.e. to have something like:

```Scala
case class AppState(
  app: AppDefinition,
  version: Timestamp,
  instances: Int
)
```

**Comment by ConnorDoyle** [comment]
The underlying question is "what does the task version mean?"  Right now an AppDefinition models a request for some state.  Tasks that are launched to achieve that state are tagged with the version of the request.  If we stick with that definition, then the current behavior is internally consistent.  IMO updating the version of already-launched tasks makes this a much harder concept to explain.

**Comment by bobrik** [comment]
@ConnorDoyle downscaling an app marks all running instances after deployment as out of date. That doesn't look like very consistent to me.

I like `AppState` from @sttts. Can anything else except `instances` be changed that would not require task rescheduling? Looks like `ports` are ephemeral an can be changed without restarts. This way version changes, app definition changes, tasks are not rescheduled but out of date yet again. I think this scenario should be considered too.

**Comment by mlunoe** [comment]
@bobrik We are talking about adding moment.js to handle the display of relative times for the version field: "Just now", "An hour ago" and "Three days ago": https://github.com/mesosphere/marathon/issues/1025

Will this not solve the problem without changing the backend?

**Comment by bobrik** [comment]
@mlunoe just like I said: https://github.com/mesosphere/marathon/issues/1025#issuecomment-70313812

> I'm ok with relative time if you could get absolute values in tooltip or with click (like in mesos ui).

**Comment by mlunoe** [comment]
Yes, tooltip is definitely part of that solution. Sorry I didn't call that out.

**Comment by sttts** [comment]
I guess with the relative dates this pr is obsolete.

**Pull request closed without merging**
