### PR TITLE
Update Marathon-ui to version 1.3.1

### PR DESCRIPTION
**Pull request by Poltergeist**
Release with few bugfixes as this one MARATHON-8255.

JIRA issues: DCOS_OSS-3652

### CODE REVIEW

**Comment by Poltergeist** [comment]
I am not sure if the ui was build so this PR is checking if it worked. :-)

**Comment by ichernetsky** [comment]
It seems that the UI release has not been built.

**Comment by alenkacz** [comment]
@ichernetsky yeah @Poltergeist has some problem with TC jobs.

I think we should backport to 1.5 then as well. It contains a bugfix community people would love to see

**Comment by timcharper** [comment]
Why not to 1.4, also?

**Comment by jeschkies** [comment]
@kensipe the build fails with

```
download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mesosphere.com/maven/mesosphere/marathon/ui/1.3.1/ui-1.3.1.pom
```
did we release the new UI?

**Comment by alenkacz** [comment]
I did start Marathon locally and saw the UI locally.

**Pull request merged**
