### PR TITLE
abosolute paths for UCR

### PR DESCRIPTION
**Pull request by sascala**
https://jira.mesosphere.com/browse/DOCS-1809

### CODE REVIEW

**Comment by unterstein** [comment]
Documentation changes for https://jira.mesosphere.com/browse/DCOS-13418
Code changes in https://phabricator.mesosphere.com/D659

**Comment by jdef** [comment]
yep, looks ready to merge once the code has landed

**Comment by unterstein** [comment]
Code and docs landed ❤️
Thanks for documentation upgrade!

**Comment by jdef** [comment]
is there a JIRA to track the backport of this for 1.4?

**Comment by meichstedt** [comment]
@jdef The original ticket https://jira.mesosphere.com/browse/DCOS-13418 was only targeted for 1.10. The fact that this PR has a fix version 1.4 (and the DOCS ticket a fix version 1.9.1) is an error afaict.

**Pull request merged**
