### PR TITLE
Fixes #4028: First health check is scheduled immediately after the task was launched.

### LINKED ISSUE #4028: Marathon remains "Deploying" status when container has already deployed
When I deploy nginx with following JSON definition:

```
{
    "id": "nginx",
    "labels": {
        "HAPROXY_GROUP": "external"
    },
    "cpus": 0.2,
    "mem": 20.0,
    "instances": 2,
    "healthChecks": [{
        "path": "/"
    }],
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "nginx",
            "network": "BRIDGE",
            "portMappings": [{ "containerPort": 80, "hostPort": 0, "servicePort": 80, "protocol": "tcp" }]
        }
    }
}
```

2 instance of nginx containers start immediately because I have pulled nginx image. I can find that nginx containers are running and I can visit nginx through browser. However, the marathon UI shows that the nginx application is still "Deploying". After about **60 seconds**, its status change to "RUNNING".

I found this is related to **healthChecks**, more specifically, the  **intervalSeconds** of **healthChecks**:
- intervalSeconds (Optional. Default: 60): Number of seconds to wait between health checks

So I set **intervalSeconds** to 5:

```
{
    "id": "nginx",
    "labels": {
        "HAPROXY_GROUP": "external"
    },
    "cpus": 0.2,
    "mem": 20.0,
    "instances": 2,
    "healthChecks": [{
        "path": "/",
        "intervalSeconds": 5
    }],
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "nginx",
            "network": "BRIDGE",
            "portMappings": [{ "containerPort": 80, "hostPort": 0, "servicePort": 80, "protocol": "tcp" }]
        }
    }
}
```

Then I can find that the status of nginx application change to "RUNNING" in about 5 seconds.

However, this is not a good solution. Because when the application is running, we don't need to check the healthy in every 5 seconds. We only need to check the healthy with high frequency when we first start the application.

### PR DESCRIPTION
**Pull request by zen-dog**
First health check is now applied DefaultFirstHealthCheckTime (1s by default) after the task was successfully launched. scheduler.schedule(...) is used instead of scheduler.scheduleOnce(...) which simplifies code a bit.

- a few minor scalastyle complains also fixed

### CODE REVIEW

**Comment by unterstein** [comment]
lgtm

should this be configurable in the future?

**Comment by jdef** [comment]
* after successfully launched, or reported as RUNNING?
* and why only 1s? why not 5s? 10s? what's driving this?

**Comment by zen-dog** [comment]
> It seems to me that the need is a higher frequency health check poll until the task reports healthy.
I agree, however that might not be necessary at all except for the very first health check. And yes - 1s seems to be arbitrary, but we can make it configurable via the UI (or just JSON) like the other parameters.

> ... to pick some random value between 0 and intervalSeconds/2
This would be then a source of some-times-it-works-and-sometimes-it-doesn't complains. I'd rather keep it simple, provide some meaningful default, and let the user configure it in their special cases.

**Comment by jdef** [comment]
:( to even more parameters. the health check api shouldn't get any more
complicated. given that we're eventually pushing all health checks to mesos
anyway ... my former suggestion is probably moot. so lets keep it simple.
if we're going to make 1s configurable, let's please avoid polluting the API

On Fri, Sep 9, 2016 at 11:29 AM, Aleksey Dukhovniy <notifications@github.com

**Comment by aquamatthias** [comment]
Close in favor of #4368

**Pull request closed without merging**
