### PR TITLE
Changing MarathonUI version to 1.1.6

### PR DESCRIPTION
**Pull request by wavesoft**
Changing marathon UI version to the latest release (1.1.6)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/mesosphere/marathon/pull/4857" target="_blank">ReviewNinja

**Comment by unterstein** [comment]
retest this please

**Comment by bakstad** [comment]
Could somebody please fix this? We really need this version.

**Comment by unterstein** [comment]
Thanks!

```
    .  o ..                  
     o . o o.o                
          ...oo               
            __[]__          Shippin'  
         __|_o_o_o\__         it!
         \""""""""""/         
          \. ..  . /          
     ^^^^^^^^^^^^^^^^^^^^
```

**Comment by bakstad** [comment]
Is there any chance of updating the 1.3.x release as well (1.3.7)? 1.4.x is still only in RC.

**Pull request merged**
