### PR TITLE
Introducing less-variables for css colours.

### PR DESCRIPTION
**Pull request by aldipower**
Relating to #1057 .

Maybe we could normalize some colors to reduce the amount of the variables.
There are a lot of near neighbour colors.

### CODE REVIEW

**Comment by pyronicide** [comment]
Moving to variables is a great change. Unfortunately, the names don't tell me what I'm supposed to be using them for. I'd like to see names more like `color-error` than `color-valencia`. If we're going to name these, then we need to make it clear what the colors get used for.

**Comment by aldipower** [comment]
:grin:
Yes, that is a good point, you're absolutly right. :) I will change this. 
My intention was that a single color could used for multiple purposes.
F.ex. @color-shuttle-gray is used on 4 different purposes, as background for buttons, border color for form control, background in the progress bar.. I wanted to reduce the amount of variables, but this is meaningless.

**Comment by aldipower** [comment]
Will do it like this:
http://sachagreif.com/sass-color-variables/

**Comment by mlunoe** [comment]
I would rather that we name them like @pyronicide suggests, and if they happen to be used for multiple purposes, say `color-success` and `color-active`, then declare two names and give them the same value. In this specific case I'm thinking of the button colours, and active tab/link colours. It's not very descriptive for their purpose to call them `border_color` and `link_color`, in my opinion

**Comment by aldipower** [comment]
Yes, that is a good approach and was also my intention. border_color would also be meaningless.
I will take a look on which places in the less-file it makes sense to introduce meaningful variables.
Here it makes sense:
```
.has-error .help-block,
.has-error .control-label,
.has-error .radio,
.has-error .checkbox,
.has-error .radio-inline,
.has-error .checkbox-inline {
  color: @color-error;
}
```
But what should I do here, could be @color-page-background?:
```
.modal-content {
  background-color: @color-ebony-clay;
}
```
And colors that do not have an associated function, like a simple border? There I would use the color name.
```
.form-control {
  background: @color-white-smoke;
  border-color: @color-shuttle-grey;
  color: @color-mortar;
}
```
else we end up in single variables for each meaning. Which would make this approach a little bit of sensless??
```
.form-control {
  background: @color-form-background;
  border-color: @color-form-border;
  color: @color-form-text;
}
```

**Comment by mlunoe** [comment]
That sounds good.

The main purpose here is also to make it configurable. Take a look at how the name the variables in bootstrap: https://github.com/twbs/bootstrap/blob/master/less/variables.less
I think colours that we use multiple places makes sense to make configurable. An example is `#f6f6f6`. We could name e.g. form-control background `@input-bg` and btn-default colour `@btn-default-color`. This way it would be easy to see which colours are used where and configure it.

Does that make sense?

And again inspired by bootstrap we could keep these in a separate stylesheet, e.g. `variables.less`.

**Comment by drexin** [comment]
@aldipower What's the status of this?

**Comment by mlunoe** [comment]
Closing for now. We can re-open, when we get more time to work on this.

**Pull request closed without merging**
