### PR TITLE
Limit the number of concurrent http requests.

### LINKED ISSUE #1710: Too many simultaneous requests will kill Marathon
There are customers, that hit the Marathon API very often (DDOS). This will effectively kill Marathon.

### PR DESCRIPTION
**Pull request by aquamatthias**
Fixes #1710 Too many simultaneous requests will kill Marathon.

### CODE REVIEW

**Comment by kolloch** [comment]
tests are failing

**Comment by felixb** [comment]
does this effect SSE connections too?

**Comment by aquamatthias** [comment]
Only during Connection Time for the initial  request.

**Comment by aquamatthias** [comment]
BTW: coveralls reports back the coverage. I defined the boundaries to <60% overall and 2% drop as failure.

**Comment by gkleiman** [comment]
:+1:

**Pull request merged**
