### PR TITLE
External volumes docs

### PR DESCRIPTION
**Pull request by sascala**
This should not appear on the site until 1.7 GAs (currently slated for Monday, 5/16).

### CODE REVIEW

**Comment by sascala** [comment]
Does this look OK to you too, @branden ?

**Comment by jdef** [comment]
lgtm

**Comment by branden** [comment]
👍

**Comment by jdef** [comment]
docs say that relative-paths are allowed for mesos container, but actually a "no-slashes" rule is enforced by Marathon when using MESOS containers. For example, when using MESOS containers the path "foo" is acceptable, but "foo/bar" is not.

**Pull request merged**
