### PR TITLE
Update License Copyright

### PR DESCRIPTION
**Pull request by kolloch**

### CODE REVIEW

**Comment by aquamatthias** [comment]
I am not a license expert: does this mean we defined this license in 2013?
If we say 2013-2016: what happens in 2017?

**Comment by kolloch** [comment]
I am not a license expert either but I have seen people updating their copyrights. You cannot just extend the copyright into the future, I guess.

/cc @florianleibert

**Comment by nklovejoy** [comment]
The date should reflect the creation year.  Really, though, you could put 2041 and it would have no practical legal significance in the US or EU.

**Comment by aquamatthias** [comment]
Than I will just leave it as is `2013`

**Pull request closed without merging**
